(() => {
  const $ = id => document.getElementById(id);
  const esc = value => String(value ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const rupees = value => new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(Number(value));
  const when = value => new Date(value).toLocaleString('en-IN');
  let offset = 0;
  function sync(serverNow) {offset=new Date(serverNow).getTime()-Date.now();}
  function timer(a) {
    if(a.phase==='ended'||a.phase==='cancelled') return a.phase==='cancelled'?'Cancelled':'Ended';
    const target=a.phase==='upcoming'?a.starts_at:a.ends_at;
    return `<span data-deadline="${esc(target)}" data-start="${a.phase==='upcoming'}"></span>`;
  }
  function tick() {
    document.querySelectorAll('[data-deadline]').forEach(el=>{
      const seconds=Math.max(0,Math.ceil((new Date(el.dataset.deadline).getTime()-Date.now()-offset)/1000));
      el.textContent=seconds===0?'Updating status…':`${el.dataset.start==='true'?'Starts in':'Ends in'} ${Math.floor(seconds/3600)}h ${Math.floor(seconds%3600/60)}m ${seconds%60}s`;
    });
  }
  function card(a,admin=false) {
    if(!admin)return dealerCard(a);
    return `<article class="lot-card">${a.cover_image?`<img src="${esc(a.cover_image)}" alt="${esc(a.brand)} ${esc(a.model)}" loading="lazy">`:''}<span class="lot-phase">LOT #${esc(a.id)} · ${esc(a.phase)}</span><h3>${esc(a.brand)} ${esc(a.model)}</h3><p>${esc(a.year)} · ${a.kilometers_driven==null?'KM not recorded':esc(a.kilometers_driven)+' km'} · Bike #${esc(a.bike_id)}</p><div class="lot-price">${rupees(a.highest_bid??a.starting_price)}</div><p>${a.highest_bid==null?'Starting price':esc(a.bid_count)+' bids'}${a.is_leading?' · You lead':''}${a.is_winner?' · You won':''}</p><p>Leading dealer: <strong>${esc(a.leading_name||'No bids yet')}</strong> · ${esc(a.leading_business||'')}</p><div class="lot-timer">${timer(a)}</div><p>${a.status==='closed'?a.result==='sold'?'Highest bid recorded — see Auction Controls for admin decision':'No winner — reserve not met':''}</p>${admin?`<p>Starts ${esc(when(a.starts_at))}<br>Ends ${esc(when(a.ends_at))}<br>Reserve ${rupees(a.reserve_price)}</p>${a.winner_name?`<p>Winner: ${esc(a.winner_name)}<br>${esc(a.winner_email)}<br>Arrange payment and handover.</p>`:''}${a.status==='open'&&Number(a.bid_count)===0?`<button type="button" data-cancel="${esc(a.id)}">Cancel auction</button>`:''}`:`<button type="button" data-lot="${esc(a.id)}">VIEW BIKE${a.phase==='live'?' & BID':''} →</button>`}</article>`;
  }
  async function json(res,onData) {const data=await res.json().catch(()=>({}));onData?.(data);if(!res.ok)throw new Error(data.error||'Request failed');return data;}
  function pager(prefix,page,total) {$(prefix+'Prev').disabled=page===1;$(prefix+'Next').disabled=page*50>=Number(total);$(prefix+'Page').textContent=`Page ${page} of ${Math.max(1,Math.ceil(total/50))}`;}
  setInterval(tick,1000);
  if($('auctionForm')) {
    let ready=false,page=1,accountPage=1,loading=false;
    const api=(url,opts)=>window.bkAdminApi(url,opts).then(json);
    function defaults(){for(const [key,delta] of [['startsAt',300000],['endsAt',3900000]]){const date=new Date(Date.now()+delta);date.setMinutes(date.getMinutes()-date.getTimezoneOffset());$('auctionForm').elements[key].value=date.toISOString().slice(0,16);}}
    defaults();
    async function loadAuctions(){const data=await api('/api/auctions?page='+page);sync(data.serverNow);$('adminAuctions').innerHTML=data.rows.map(a=>card(a,true)).join('')||'<p class="lot-empty">No auctions scheduled yet.</p>';pager('admin',page,data.total);tick();}
    async function loadAccounts(){const data=await api('/api/admin/accounts?page='+accountPage);$('accountList').innerHTML=data.rows.map(u=>`<div class="account-row"><div><strong>${esc(u.full_name)}</strong><small>${esc(u.email)} · ${esc(u.role)}</small><small>${esc(u.business_name||'Business not recorded')} · Mobile: ${esc(u.phone||'Not recorded')}</small><small>${u.is_verified?'Approved':'Pending approval'} · ${u.is_active?'Active':'Disabled'}</small></div><div>${!u.is_verified?`<button type="button" data-account="${esc(u.id)}" data-field="is_verified" data-value="true">Approve</button>`:''}<button type="button" data-account="${esc(u.id)}" data-field="is_active" data-value="${!u.is_active}">${u.is_active?'Disable':'Enable'}</button></div></div>`).join('')||'<p>No dealer accounts yet.</p>';pager('account',accountPage,data.total);}
    let bikeOptionsGeneration=0;
    async function loadBikeOptions(){const generation=++bikeOptionsGeneration;const selected=$('bikeOptions').value;const data=await api('/api/admin/operations/bike-options?search='+encodeURIComponent($('auctionBikeSearch')?.value||''));if(generation!==bikeOptionsGeneration)return;$('bikeOptions').innerHTML='<option value="">Choose a bike from inventory</option>'+data.rows.filter(b=>b.status!=='sold').map(b=>`<option value="${esc(b.id)}">#${esc(b.id)} · ${esc(b.brand)} ${esc(b.model)} · ${esc(b.registration_number||b.year)} (${esc(b.status)})</option>`).join('');$('bikeOptions').value=selected;}
    window.bkPrepareAuctionBike=async bikeId=>{if(!window.bkAdminPermissions?.includes('auctions'))throw Error('Auction access required');const d=await api('/api/admin/bikes/'+encodeURIComponent(bikeId)),b=d.bike;if(b.status==='sold')throw Error('Sold bikes cannot be scheduled for auction');++bikeOptionsGeneration;const form=$('auctionForm');$('tab-create').click();$('auctionBikeSearch').value=String(b.registration_number||b.id);$('bikeOptions').innerHTML='<option value="">Choose a bike from inventory</option>'+`<option value="${esc(b.id)}">#${esc(b.id)} · ${esc(b.brand)} ${esc(b.model)} · ${esc(b.registration_number||'')} (${esc(b.status)})</option>`;$('bikeOptions').value=String(b.id);for(const key of ['startingPrice','minIncrement','reservePrice'])form.elements[key].value=key==='minIncrement'?'500':'';defaults();$('auctionAdminMsg').textContent='Inspection bike #'+b.id+' selected. Saved vehicle details, checklist and photos will appear in the auction. Set prices and times, then Create Auction.';form.scrollIntoView?.({behavior:'smooth',block:'start'});};
    window.addEventListener('bk-reauction',async e=>{try{const a=e.detail;$('auctionBikeSearch').value=String(a.bike_id);await loadBikeOptions();if(![...$('bikeOptions').options].some(o=>String(o.value)===String(a.bike_id)))throw Error('Vehicle is no longer eligible for auction');$('bikeOptions').value=String(a.bike_id);const form=$('auctionForm');for(const key of ['startingPrice','minIncrement','reservePrice'])form.elements[key].value=a[({startingPrice:'starting_price',minIncrement:'min_increment',reservePrice:'reserve_price'})[key]];defaults();$('tab-create').click();$('auctionAdminMsg').textContent='Re-auction from lot #'+a.id+'. Review prices and choose new times, then Create Auction. Previous bids stay in the old lot.';}catch(err){$('completedMsg').textContent=err.message;}});
    window.addEventListener('bk-admin-ready',async()=>{ready=true;try{const access=await api('/api/admin/operations/access');window.bkAdminPermissions=access.scopes;await Promise.all([...(access.scopes.includes('auctions')?[loadAuctions(),loadBikeOptions()]:[]),...(access.scopes.includes('accounts')?[loadAccounts()]:[])]);}catch(e){$('auctionAdminMsg').textContent=e.message;}});
    window.addEventListener('bk-bikes-changed',()=>{if(window.bkAdminPermissions&&!window.bkAdminPermissions.includes('auctions'))return;loadBikeOptions().catch(e=>$('auctionAdminMsg').textContent=e.message);});
    $('auctionBikeFind')?.addEventListener('click',()=>loadBikeOptions().catch(e=>$('auctionAdminMsg').textContent=e.message));
    window.addEventListener('bk-admin-tab',()=>{if(!ready||window.bkAdminPermissions&&!window.bkAdminPermissions.includes('accounts'))return;loadAccounts().catch(e=>$('accountMsg').textContent=e.message);});
    $('auctionForm').addEventListener('submit',async e=>{e.preventDefault();const form=e.currentTarget,button=e.submitter||form.querySelector('button[type="submit"]');button.disabled=true;$('auctionAdminMsg').textContent='Scheduling…';try{const body=Object.fromEntries(new FormData(form));body.startsAt=new Date(body.startsAt).toISOString();body.endsAt=new Date(body.endsAt).toISOString();const data=await api('/api/auctions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});$('auctionAdminMsg').textContent=`Auction #${data.auction.id} scheduled.`;form.reset();defaults();page=1;await loadAuctions();}catch(err){$('auctionAdminMsg').textContent=err.message;}finally{button.disabled=false;}});
    $('adminAuctions').addEventListener('click',async e=>{const button=e.target.closest('[data-cancel]');if(!button)return;button.disabled=true;try{await api(`/api/auctions/${button.dataset.cancel}/cancel`,{method:'POST'});await loadAuctions();$('auctionAdminMsg').textContent='Auction cancelled.';}catch(err){$('auctionAdminMsg').textContent=err.message;button.disabled=false;}});
    $('accountList').addEventListener('click',async e=>{const b=e.target.closest('[data-account]');if(!b)return;b.disabled=true;try{await api('/api/admin/accounts/'+b.dataset.account,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({[b.dataset.field]:b.dataset.value==='true'})});await loadAccounts();$('accountMsg').textContent='Account updated.';}catch(err){$('accountMsg').textContent=err.message;b.disabled=false;}});
    for(const [id,delta,accounts] of [['adminPrev',-1,false],['adminNext',1,false],['accountPrev',-1,true],['accountNext',1,true]])$(id).onclick=()=>{if(accounts)accountPage+=delta;else page+=delta;(accounts?loadAccounts():loadAuctions()).catch(e=>{$('auctionAdminMsg').textContent=e.message;});};
    setInterval(async()=>{if(!ready||loading||window.bkAdminPermissions&&!window.bkAdminPermissions.includes('auctions')||document.hidden||!$('dashboardPanel').classList.contains('active'))return;loading=true;try{await loadAuctions();}catch(e){$('auctionAdminMsg').textContent=e.message;}finally{loading=false;}},5000);
    return;
  }
  if(!$('dealerLogin'))return;
  let token=null,refreshing=null,currentUser=null,phase='live',rows=[],page=1,selected=null,busy=false,submitting=false,requestId=null,requestAmount=null;
  let nativeDevice=window.BKPushDevice||null,lastPushRegistration='',registeringPush=null,loggingOut=false;
  let pendingPushToken='',pendingPushRequest=null,lastPendingPush='';
  try{pendingPushToken=localStorage.getItem('bk-pending-push')||'';}catch{}
  function rememberPendingPush(value){pendingPushToken=value||'';lastPendingPush='';try{if(value)localStorage.setItem('bk-pending-push',value);else localStorage.removeItem('bk-pending-push');}catch{}registerPendingPush();}
  function registerPendingPush(){
    if(token||!pendingPushToken||!nativeDevice?.token||pendingPushRequest)return;
    const fingerprint=pendingPushToken+':'+nativeDevice.token+':'+nativeDevice.enabled;
    if(lastPendingPush===fingerprint)return;
    pendingPushRequest=(async()=>{try{
      const res=await fetch('/api/notifications/pending-devices',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({pendingPushToken,token:nativeDevice.token,enabled:nativeDevice.enabled})});
      if(res.ok)lastPendingPush=fingerprint;
      else if(res.status===401||res.status===403)rememberPendingPush('');
    }catch{console.warn('Approval alerts could not be registered; retrying.');}})().finally(()=>pendingPushRequest=null);
    return pendingPushRequest;
  }
  function registerPush(){
    if(!token||!currentUser||!['dealer','bidder'].includes(currentUser.role)||!nativeDevice?.token||loggingOut)return;
    if(registeringPush)return registeringPush;
    const fingerprint=currentUser.id+':'+nativeDevice.token+':'+nativeDevice.enabled;
    if(lastPushRegistration===fingerprint)return;
    registeringPush=(async()=>{try{await api('/api/notifications/devices',{method:nativeDevice.enabled?'POST':'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({token:nativeDevice.token})});lastPushRegistration=fingerprint;}catch(e){console.warn('Auction alerts could not be registered; retrying on next refresh.');}})().finally(()=>registeringPush=null);return registeringPush;
  }
  window.addEventListener('bk-push-token',e=>{nativeDevice=e.detail;registerPush();registerPendingPush();});
  registerPendingPush();
  async function openNotificationAuction(){
    const id=new URLSearchParams(location.search).get('auction');
    if(!token||!id||!/^[1-9]\d*$/.test(id))return;
    selected=id;
    try{await details(id,true);if(!$('lotDialog').open)$('lotDialog').showModal();const url=new URL(location.href);url.searchParams.delete('auction');history.replaceState(null,'',url.pathname+url.search+url.hash);}catch(e){$('dealerMsg').textContent=e.message;selected=null;}
  }
  const cardState=new Map();
  let filters={},loadSequence=0;
  function state(id){if(!cardState.has(String(id)))cardState.set(String(id),{index:0,amount:null,pending:false,message:''});return cardState.get(String(id));}
  function gallery(a){const images=a.images?.length?a.images:a.cover_image?[{image_url:a.cover_image}]:[];return `<div class="card-gallery" data-gallery="${esc(a.id)}" tabindex="0" aria-label="Bike photos — swipe to browse">${images.length?images.map((img,i)=>`<div class="gallery-slide"><img src="${esc(img.image_url)}" alt="${esc(a.brand)} ${esc(a.model)} — photo ${i+1}" loading="lazy"></div>`).join(''):'<div class="gallery-slide photo-missing">No photo available</div>'}</div>${images.length>1?`<div class="gallery-controls"><button type="button" data-photo="${esc(a.id)}" data-direction="-1" aria-label="Previous photo">←</button><span>${images.length} photos · Swipe to browse</span><button type="button" data-photo="${esc(a.id)}" data-direction="1" aria-label="Next photo">→</button></div>`:''}`;}
  function dealerCard(a){const outbid=a.phase==='live'&&a.my_bid!=null&&!a.is_leading;const st=state(a.id),minimum=a.minimum_bid??(a.highest_bid==null?Number(a.starting_price):Number(a.highest_bid)+Number(a.min_increment));return `<article class="lot-card">${gallery(a)}<span class="lot-phase">LOT #${esc(a.id)} · ${esc(a.phase)}</span><h3>${esc(a.brand)} ${esc(a.model)}</h3><p>${esc(a.year)} · ${esc(a.kilometers_driven??'—')} km · ${esc(a.registration_number||'Bike #'+a.bike_id)}</p><div class="card-bid-summary"><div class="card-bid-stats"><div class="${outbid?'bid-outbid':''}"><small>${a.highest_bid==null?'Starting price':'Highest bid'}</small>${outbid?'<span class="outbid-mark" role="status">● Outbid</span>':''}<strong>${rupees(a.highest_bid??a.starting_price)}</strong></div><div><small>Your bid</small><strong>${a.my_bid==null?'—':rupees(a.my_bid)}</strong></div></div><button class="card-details" type="button" data-lot="${esc(a.id)}">View bike details →</button></div><p>${esc(a.bid_count)} bids${a.is_winner?' · You won':a.is_leading?' · You lead':a.my_bid!=null&&a.phase==='live'?' · Outbid':''}</p><div class="lot-timer">${timer(a)}</div>${a.phase==='live'&&currentUser?.role!=='admin'?`<form data-inline-bid="${esc(a.id)}"><label for="amount-${esc(a.id)}">Your bid amount (₹)</label><div class="quick-bids">${[1,2,5].map(n=>`<button type="button" data-increase="${esc(a.id)}" data-multiple="${n}" ${st.pending?'disabled':''}>+${rupees(Number(a.min_increment)*n)}</button>`).join('')}</div><div class="inline-bid-controls"><button type="button" data-increase="${esc(a.id)}" data-multiple="-1" aria-label="Decrease bid" ${st.pending?'disabled':''}>−</button><input id="amount-${esc(a.id)}" data-inline-amount="${esc(a.id)}" name="amount" type="number" min="${esc(minimum)}" max="1000000000" step="1" required value="${esc(st.amount??minimum)}" ${st.pending?'disabled':''}><button type="button" data-increase="${esc(a.id)}" data-multiple="1" aria-label="Increase bid" ${st.pending?'disabled':''}>+</button><button type="submit" ${st.pending?'disabled':''}>${st.pending?'Submitting…':'Bid Now'}</button></div></form>`:''}${st.message?`<p class="card-message" role="status">${esc(st.message)}</p>`:''}</article>`;}
  async function refresh(){const res=await fetch('/api/auth/refresh',{method:'POST',credentials:'include'});if(!res.ok)return false;const data=await res.json();token=data.accessToken;return Boolean(token);}
  function signedOut(message='Please log in to view auctions.'){document.body?.classList.remove('dealer-mode');if($('dealerHeading'))$('dealerHeading').textContent='Bid on quality used bikes.';if($('dealerIntro'))$('dealerIntro').textContent='Log in to review bike details, follow the timer and place your bid.';token=null;currentUser=null;loadSequence++;cardState.clear();$('dealerLogin').hidden=false;$('dealerSession').hidden=true;if($('dealerAccess'))$('dealerAccess').hidden=false;if($('accountMenuLabel'))$('accountMenuLabel').textContent='☰ Menu';if($('accountMenu'))$('accountMenu').open=false;$('dealerAuctions').innerHTML='';$('dealerMsg').textContent=message;$('lotDialog').close();}
  async function api(url,opts={}){const headers=new Headers(opts.headers||{});const send=()=>{headers.set('Authorization','Bearer '+token);return fetch(url,{...opts,headers,credentials:'include'});};let res=await send();if(res.status===401){if(!refreshing)refreshing=refresh().finally(()=>refreshing=null);if(await refreshing)res=await send();else signedOut('Session expired. Please log in again.');}return json(res);}
  function render(){const active=document.activeElement?.dataset?.inlineAmount;$('dealerAuctions').innerHTML=rows.map(a=>card(a)).join('')||'<p class="lot-empty">No auctions match this view.</p>';document.querySelectorAll('[data-gallery]').forEach(el=>{el.scrollLeft=state(el.dataset.gallery).index*el.clientWidth;});if(active)$('amount-'+active)?.focus?.({preventScroll:true});tick();}
  async function load(){const sequence=++loadSequence,params=new URLSearchParams({page,phase,...filters});const data=await api('/api/auctions?'+params);if(sequence!==loadSequence||!token)return;rows=data.rows;sync(data.serverNow);render();pager('dealer',page,data.total);}
  if($('auctionSearch'))$('auctionSearch').onsubmit=e=>{e.preventDefault();filters=Object.fromEntries([...new FormData(e.currentTarget)].filter(([,v])=>String(v).trim()));page=1;load().catch(e=>$('dealerMsg').textContent=e.message);};
  if($('clearAuctionSearch'))$('clearAuctionSearch').onclick=()=>{$('auctionSearch').reset();filters={};page=1;load().catch(e=>$('dealerMsg').textContent=e.message);};
  async function signedIn(user){rememberPendingPush('');currentUser=user;loggingOut=false;lastPushRegistration='';registerPush();phase='live';page=1;document.body?.classList.add('dealer-mode');document.querySelectorAll('[data-phase]').forEach(el=>el.setAttribute('aria-pressed',String(el.dataset.phase==='live')));if($('dealerHeading'))$('dealerHeading').textContent='';if($('dealerIntro'))$('dealerIntro').textContent='';$('dealerLogin').hidden=true;$('dealerSession').hidden=false;if($('dealerAccess'))$('dealerAccess').hidden=true;if($('authDialog'))$('authDialog').close();if($('accountMenuLabel'))$('accountMenuLabel').textContent='☰ Menu';if($('accountMenu'))$('accountMenu').open=false;if($('accountMsgMenu'))$('accountMsgMenu').textContent='';$('dealerName').textContent=(user.full_name||user.email)+' · '+user.role;$('dealerMsg').textContent='';await load();$('live').scrollIntoView?.({behavior:'smooth',block:'start'});await openNotificationAuction();}
  function openAuth(view='login'){if(token)return;const registration=view==='register';$('dealerLogin').hidden=registration;if($('registrationPane'))$('registrationPane').hidden=!registration;document.querySelectorAll('.auth-tabs [data-auth-view]').forEach(el=>el.setAttribute('aria-pressed',String(el.dataset.authView===view)));if($('accountMenu'))$('accountMenu').open=false;if($('authDialog')&&!$('authDialog').open)$('authDialog').showModal();}
  document.querySelectorAll('[data-auth-view]').forEach(button=>button.addEventListener('click',()=>openAuth(button.dataset.authView)));
  document.querySelectorAll('a[href="#register"]').forEach(link=>link.addEventListener('click',e=>{e.preventDefault();openAuth('register');}));
  document.querySelectorAll('a.main-btn[href="#live"]').forEach(link=>link.addEventListener('click',e=>{if(!token){e.preventDefault();openAuth('login');}}));
  if($('closeAuth'))$('closeAuth').onclick=()=>{$('authDialog').close();};
  $('dealerLogin').onsubmit=async e=>{e.preventDefault();const form=e.currentTarget,button=e.submitter||form.querySelector('button[type="submit"]');button.disabled=true;$('dealerMsg').textContent='';if($('accountMsgMenu'))$('accountMsgMenu').textContent='Signing in…';try{const response=await fetch('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},credentials:'include',body:JSON.stringify(Object.fromEntries(new FormData(form)))});const data=await json(response,payload=>{if(payload.pendingPushToken)rememberPendingPush(payload.pendingPushToken);});token=data.accessToken;form.reset();await signedIn(data.user);}catch(err){if($('accountMsgMenu'))$('accountMsgMenu').textContent=err.message;else $('dealerMsg').textContent=err.message;}finally{button.disabled=false;}};
  document.querySelectorAll('#accountMenu a').forEach(link=>link.addEventListener('click',()=>{$('accountMenu').open=false;}));
  $('dealerLogout').onclick=async()=>{loggingOut=true;if(registeringPush)await registeringPush;if(nativeDevice?.token&&token){try{await api('/api/notifications/devices',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({token:nativeDevice.token})});}catch(e){loggingOut=false;$('dealerMsg').textContent='Could not disconnect auction alerts. Check your connection and try logging out again.';return;}}lastPushRegistration='';await fetch('/api/auth/logout',{method:'POST',credentials:'include'}).catch(()=>{});signedOut('Logged out.');};
  $('dealerRegister').onsubmit=async e=>{e.preventDefault();const form=e.currentTarget,b=e.submitter||form.querySelector('button[type="submit"]');b.disabled=true;try{const body={...Object.fromEntries(new FormData(form)),role:'dealer'};const data=await json(await fetch('/api/auth/register',{method:'POST',headers:{'Content-Type':'application/json'},credentials:'include',body:JSON.stringify(body)}));rememberPendingPush(data.pendingPushToken);$('registerMsg').textContent=data.message;form.reset();}catch(err){$('registerMsg').textContent=err.message;}finally{b.disabled=false;}};
  document.querySelectorAll('[data-phase]').forEach(b=>b.onclick=()=>{phase=b.dataset.phase;document.querySelectorAll('[data-phase]').forEach(el=>el.setAttribute('aria-pressed',String(el===b)));page=1;load().catch(e=>$('dealerMsg').textContent=e.message);});
  document.querySelectorAll('a[href="#upcoming"]').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();phase='upcoming';document.querySelectorAll('[data-phase]').forEach(el=>el.setAttribute('aria-pressed',String(el.dataset.phase===phase)));page=1;load().catch(e=>$('dealerMsg').textContent=e.message);$('live').scrollIntoView({behavior:'smooth'});}));
  for(const [id,delta] of [['dealerPrev',-1],['dealerNext',1]])$(id).onclick=()=>{page+=delta;load().catch(e=>$('dealerMsg').textContent=e.message);};
  let detailTab='info';
  function detailRows(rows){return '<dl class="vehicle-rows">'+rows.map(([label,value])=>`<div><dt>${esc(label)}</dt><dd>${esc(value==null||value===''?'Not recorded':value)}</dd></div>`).join('')+'</dl>';}
  function applyDetailTab(){document.querySelectorAll('[data-detail-tab]').forEach(el=>{const active=el.dataset.detailTab===detailTab;el.setAttribute('aria-selected',String(active));el.tabIndex=active?0:-1;});document.querySelectorAll('[data-detail-panel]').forEach(el=>el.hidden=el.dataset.detailPanel!==detailTab);}
  async function details(id,initial=false){const data=await api('/api/auctions/'+id);if(selected!==id)return;const a=data.auction,b=data.bike,profile=b.detail_profile||{};if(initial)detailTab='info';const dialogScroll=$('lotDialog').scrollTop;sync(data.serverNow);
    $('lotDetail').innerHTML=`<div class="vehicle-title">Vehicle Details</div>${gallery({id:'detail-'+id,brand:b.brand,model:b.model,images:b.images})}<h2>${esc(b.brand)} ${esc(b.model)}</h2><div class="vehicle-summary"><span>Lot #${esc(a.id)} · ${esc(a.phase)}</span><strong>${rupees(a.highest_bid??a.starting_price)}<small>${a.highest_bid==null?'Starting price':'Highest bid'}</small></strong></div><div class="lot-timer">${timer(a)}</div><p>${a.is_winner?'You won. Contact BikesKart to arrange payment and handover.':a.is_leading&&a.phase==='live'?'You are the leading bidder.':''}</p><div class="vehicle-tabs" role="tablist" aria-label="Bike details">${[['info','Vehicle Info'],['inspection','Inspection'],['description','Description']].map(([key,label])=>`<button type="button" id="vehicle-tab-${key}" role="tab" data-detail-tab="${key}" aria-controls="vehicle-panel-${key}">${label}</button>`).join('')}</div><section id="vehicle-panel-info" role="tabpanel" aria-labelledby="vehicle-tab-info" data-detail-panel="info">${detailRows([['Registration number',b.registration_number],['Chassis number',profile.chassisNumber],['Engine number',profile.engineNumber],['Registration year',profile.registrationYear],['Manufacturing year',b.year],['No. of owners',b.ownership_count],['HP status',profile.hpStatus],['NOC status',profile.nocStatus],['RC availability',profile.rcAvailable],['Keys',profile.keysCount],['Insurance',profile.insuranceStatus],['Odometer (km)',b.kilometers_driven],['Fuel type',b.fuel_type]])}</section><section id="vehicle-panel-inspection" role="tabpanel" aria-labelledby="vehicle-tab-inspection" data-detail-panel="inspection">${detailRows([['Engine Noise',profile.engineNoise],['Smoke',profile.smoke],['Self Start',profile.selfStart],['Clutch Plate',profile.clutchPlate],['Timing Chain Noise',profile.timingChainNoise],['Engine Condition',profile.engineCondition],['Battery Working',profile.batteryWorking],['Chassis',profile.chassis],['Body Line',profile.bodyLine],['Inspection notes',profile.inspectionNotes]])}</section><section id="vehicle-panel-description" role="tabpanel" aria-labelledby="vehicle-tab-description" data-detail-panel="description"><h3>Description</h3><p>${esc(b.condition_notes||'No description recorded.')}</p></section><details class="vehicle-auction-history"><summary>Auction timings & recent bids</summary><p>Starts: ${esc(when(a.starts_at))}<br>Ends: ${esc(when(a.ends_at))}</p><ol>${data.bids.map(bid=>`<li>${rupees(bid.amount)} · ${esc(when(bid.created_at))}</li>`).join('')||'<li>No bids yet.</li>'}</ol></details>`;
    applyDetailTab();document.querySelectorAll('#lotDetail [data-gallery]').forEach(el=>el.scrollLeft=state(el.dataset.gallery).index*el.clientWidth);if(!initial)$('lotDialog').scrollTop=dialogScroll;
    $('bidForm').hidden=a.phase!=='live'||currentUser?.role==='admin';$('bidAmount').min=a.minimum_bid;if(initial){$('bidAmount').value=a.minimum_bid;$('bidMsg').textContent='';requestId=null;requestAmount=null;}tick();}
  $('lotDetail').addEventListener('click',e=>{const tab=e.target.closest('[data-detail-tab]');if(tab){detailTab=tab.dataset.detailTab;applyDetailTab();return;}const button=e.target.closest('[data-photo]');if(button){const el=document.querySelector('#lotDetail [data-gallery]');if(el){const st=state(el.dataset.gallery);st.index=Math.max(0,Math.min(el.children.length-1,st.index+Number(button.dataset.direction)));el.scrollTo({left:st.index*el.clientWidth,behavior:'smooth'});}}});
  $('lotDetail').addEventListener('keydown',e=>{const tab=e.target.closest('[data-detail-tab]');if(!tab||!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();const keys=['info','inspection','description'];detailTab=e.key==='Home'?keys[0]:e.key==='End'?keys[2]:keys[(keys.indexOf(detailTab)+(e.key==='ArrowRight'?1:2))%3];applyDetailTab();$('vehicle-tab-'+detailTab).focus();});
  $('lotDetail').addEventListener('scroll',e=>{if(e.target.dataset?.gallery&&e.target.clientWidth)state(e.target.dataset.gallery).index=Math.round(e.target.scrollLeft/e.target.clientWidth);},true);
  $('lotDetail').addEventListener('error',e=>{if(e.target.tagName==='IMG'){const slide=e.target.closest('.gallery-slide');if(slide){slide.textContent='Photo unavailable';slide.classList.add('photo-missing');}}},true);
  $('dealerAuctions').onclick=async e=>{const photo=e.target.closest('[data-photo]');if(photo){const el=document.querySelector('[data-gallery="'+photo.dataset.photo+'"]');if(el){const st=state(photo.dataset.photo);st.index=Math.max(0,Math.min(el.children.length-1,st.index+Number(photo.dataset.direction)));el.scrollTo({left:st.index*el.clientWidth,behavior:'smooth'});}return;}const increase=e.target.closest('[data-increase]');if(increase){const a=rows.find(a=>String(a.id)===increase.dataset.increase),input=$('amount-'+increase.dataset.increase);if(a&&input){input.value=Math.max(Number(input.min),Math.min(1000000000,Number(input.value)+Number(a.min_increment)*Number(increase.dataset.multiple)));state(a.id).amount=input.value;}return;}const b=e.target.closest('[data-lot]');if(!b)return;selected=b.dataset.lot;try{await details(selected,true);$('lotDialog').showModal();}catch(err){$('dealerMsg').textContent=err.message;}};
  $('dealerAuctions').addEventListener('input',e=>{if(e.target.dataset.inlineAmount)state(e.target.dataset.inlineAmount).amount=e.target.value;});
  $('dealerAuctions').addEventListener('scroll',e=>{if(e.target.dataset?.gallery&&e.target.clientWidth)state(e.target.dataset.gallery).index=Math.round(e.target.scrollLeft/e.target.clientWidth);},true);
  $('dealerAuctions').addEventListener('error',e=>{if(e.target.tagName==='IMG'){const slide=e.target.closest('.gallery-slide');if(slide){slide.textContent='Photo unavailable';slide.classList.add('photo-missing');}}},true);
  $('dealerAuctions').addEventListener('submit',async e=>{const form=e.target;if(!form.dataset.inlineBid)return;e.preventDefault();const id=form.dataset.inlineBid,st=state(id);if(st.pending)return;const amount=form.elements.amount.value;st.amount=amount;if(!st.requestId||st.requestAmount!==amount){st.requestId=crypto.randomUUID();st.requestAmount=amount;}st.pending=true;st.message='Submitting bid…';render();try{const data=await api(`/api/auctions/${id}/bids`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({amount,requestId:st.requestId})});st.message='';st.requestId=null;st.amount=null;await load();}catch(err){st.message=err.message;}finally{st.pending=false;render();}});
  $('closeLot').onclick=()=>$('lotDialog').close();$('lotDialog').addEventListener('close',()=>{selected=null;requestId=null;});
  $('bidForm').onsubmit=async e=>{e.preventDefault();if(submitting||!selected)return;const id=selected,amount=$('bidAmount').value,button=e.submitter||e.currentTarget.querySelector('button[type="submit"]');submitting=true;button.disabled=true;$('bidMsg').textContent='Submitting bid…';if(!requestId||amount!==requestAmount){requestId=crypto.randomUUID();requestAmount=amount;}try{const data=await api(`/api/auctions/${id}/bids`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({amount,requestId})});$('bidMsg').textContent='';requestId=null;requestAmount=null;await details(id);await load();}catch(err){$('bidMsg').textContent=err.message;try{await details(id);}catch{}}finally{submitting=false;button.disabled=false;}};
  setInterval(async()=>{registerPendingPush();if(!token||busy||document.hidden)return;registerPush();busy=true;try{await load();if(selected&&$('lotDialog').open&&!submitting)await details(selected);}catch(err){$('dealerMsg').textContent=err.message;}finally{busy=false;}},5000);
  (async()=>{try{if(await refresh()){const data=await api('/api/auth/me');await signedIn(data.user);}}catch(err){signedOut(err.message);}})();
})();

