(() => {
  const $ = id => document.getElementById(id);
  const esc = value => String(value ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const rupees = value => new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(Number(value));
  const when = value => new Date(value).toLocaleString('en-IN');
  let offset = 0;
  function sync(serverNow) {offset=new Date(serverNow).getTime()-Date.now();}
  function timer(a) {
    if(a.phase==='ended'||a.phase==='cancelled') return a.phase==='cancelled'?'Cancelled':'Ended';
    const target=a.phase==='upcoming'?a.starts_at:a.ends_at;
    return `<span data-deadline="${esc(target)}" data-start="${a.phase==='upcoming'}"></span>`;
  }
  function tick() {
    document.querySelectorAll('[data-deadline]').forEach(el=>{
      const seconds=Math.max(0,Math.ceil((new Date(el.dataset.deadline).getTime()-Date.now()-offset)/1000));
      el.textContent=seconds===0?'Updating status…':`${el.dataset.start==='true'?'Starts in':'Ends in'} ${Math.floor(seconds/3600)}h ${Math.floor(seconds%3600/60)}m ${seconds%60}s`;
    });
  }
  function card(a,admin=false) {
    if(!admin)return dealerCard(a);
    return `<article class="lot-card">${a.cover_image?`<img src="${esc(a.cover_image)}" alt="${esc(a.brand)} ${esc(a.model)}" loading="lazy">`:''}<span class="lot-phase">LOT #${esc(a.id)} · ${esc(a.phase)}</span><h3>${esc(a.brand)} ${esc(a.model)}</h3><p>${esc(a.year)} · ${a.kilometers_driven==null?'KM not recorded':esc(a.kilometers_driven)+' km'} · Bike #${esc(a.bike_id)}</p><div class="lot-price">${rupees(a.highest_bid??a.starting_price)}</div><p>${a.highest_bid==null?'Starting price':esc(a.bid_count)+' bids'}${a.is_leading?' · You lead':''}${a.is_winner?' · You won':''}</p><div class="lot-timer">${timer(a)}</div><p>${a.status==='closed'?a.result==='sold'?'Winning bid confirmed':'No winner — reserve not met':''}</p>${admin?`<p>Starts ${esc(when(a.starts_at))}<br>Ends ${esc(when(a.ends_at))}<br>Reserve ${rupees(a.reserve_price)}</p>${a.winner_name?`<p>Winner: ${esc(a.winner_name)}<br>${esc(a.winner_email)}<br>Arrange payment and handover.</p>`:''}${a.status==='open'&&Number(a.bid_count)===0?`<button type="button" data-cancel="${esc(a.id)}">Cancel auction</button>`:''}`:`<button type="button" data-lot="${esc(a.id)}">VIEW BIKE${a.phase==='live'?' & BID':''} →</button>`}</article>`;
  }
  async function json(res) {const data=await res.json().catch(()=>({}));if(!res.ok)throw new Error(data.error||'Request failed');return data;}
  function pager(prefix,page,total) {$(prefix+'Prev').disabled=page===1;$(prefix+'Next').disabled=page*50>=Number(total);$(prefix+'Page').textContent=`Page ${page} of ${Math.max(1,Math.ceil(total/50))}`;}
  setInterval(tick,1000);
  if($('auctionForm')) {
    let ready=false,page=1,accountPage=1,loading=false;
    const api=(url,opts)=>window.bkAdminApi(url,opts).then(json);
    function defaults(){for(const [key,delta] of [['startsAt',300000],['endsAt',3900000]]){const date=new Date(Date.now()+delta);date.setMinutes(date.getMinutes()-date.getTimezoneOffset());$('auctionForm').elements[key].value=date.toISOString().slice(0,16);}}
    defaults();
    async function loadAuctions(){const data=await api('/api/auctions?page='+page);sync(data.serverNow);$('adminAuctions').innerHTML=data.rows.map(a=>card(a,true)).join('')||'<p class="lot-empty">No auctions scheduled yet.</p>';pager('admin',page,data.total);tick();}
    async function loadAccounts(){const data=await api('/api/admin/accounts?page='+accountPage);$('accountList').innerHTML=data.rows.map(u=>`<div class="account-row"><div><strong>${esc(u.full_name)}</strong><small>${esc(u.email)} · ${esc(u.role)}</small><small>${u.is_verified?'Approved':'Pending approval'} · ${u.is_active?'Active':'Disabled'}</small></div><div>${!u.is_verified?`<button type="button" data-account="${esc(u.id)}" data-field="is_verified" data-value="true">Approve</button>`:''}<button type="button" data-account="${esc(u.id)}" data-field="is_active" data-value="${!u.is_active}">${u.is_active?'Disable':'Enable'}</button></div></div>`).join('')||'<p>No dealer accounts yet.</p>';pager('account',accountPage,data.total);}
    async function loadBikeOptions(){const selected=$('bikeOptions').value;const data=await api('/api/admin/bikes?pageSize=50');$('bikeOptions').innerHTML='<option value="">Choose a bike from inventory</option>'+data.rows.filter(b=>b.status!=='sold').map(b=>`<option value="${esc(b.id)}">#${esc(b.id)} · ${esc(b.brand)} ${esc(b.model)} · ${esc(b.registration_number||b.year)} (${esc(b.status)})</option>`).join('');$('bikeOptions').value=selected;}
    window.addEventListener('bk-admin-ready',async()=>{ready=true;try{await Promise.all([loadAuctions(),loadAccounts(),loadBikeOptions()]);}catch(e){$('auctionAdminMsg').textContent=e.message;}});
    window.addEventListener('bk-bikes-changed',()=>loadBikeOptions().catch(e=>$('auctionAdminMsg').textContent=e.message));
    window.addEventListener('bk-admin-tab',()=>{if(!ready)return;loadAccounts().catch(e=>$('accountMsg').textContent=e.message);});
    $('auctionForm').addEventListener('submit',async e=>{e.preventDefault();const form=e.currentTarget,button=e.submitter||form.querySelector('button[type="submit"]');button.disabled=true;$('auctionAdminMsg').textContent='Scheduling…';try{const body=Object.fromEntries(new FormData(form));body.startsAt=new Date(body.startsAt).toISOString();body.endsAt=new Date(body.endsAt).toISOString();const data=await api('/api/auctions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});$('auctionAdminMsg').textContent=`Auction #${data.auction.id} scheduled.`;form.reset();defaults();page=1;await loadAuctions();}catch(err){$('auctionAdminMsg').textContent=err.message;}finally{button.disabled=false;}});
    $('adminAuctions').addEventListener('click',async e=>{const button=e.target.closest('[data-cancel]');if(!button)return;button.disabled=true;try{await api(`/api/auctions/${button.dataset.cancel}/cancel`,{method:'POST'});await loadAuctions();$('auctionAdminMsg').textContent='Auction cancelled.';}catch(err){$('auctionAdminMsg').textContent=err.message;button.disabled=false;}});
    $('accountList').addEventListener('click',async e=>{const b=e.target.closest('[data-account]');if(!b)return;b.disabled=true;try{await api('/api/admin/accounts/'+b.dataset.account,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({[b.dataset.field]:b.dataset.value==='true'})});await loadAccounts();$('accountMsg').textContent='Account updated.';}catch(err){$('accountMsg').textContent=err.message;b.disabled=false;}});
    for(const [id,delta,accounts] of [['adminPrev',-1,false],['adminNext',1,false],['accountPrev',-1,true],['accountNext',1,true]])$(id).onclick=()=>{if(accounts)accountPage+=delta;else page+=delta;(accounts?loadAccounts():loadAuctions()).catch(e=>{$('auctionAdminMsg').textContent=e.message;});};
    setInterval(async()=>{if(!ready||loading||document.hidden||!$('dashboardPanel').classList.contains('active'))return;loading=true;try{await loadAuctions();}catch(e){$('auctionAdminMsg').textContent=e.message;}finally{loading=false;}},5000);
    return;
  }
  if(!$('dealerLogin'))return;
  let token=null,refreshing=null,currentUser=null,phase='live',rows=[],page=1,selected=null,busy=false,submitting=false,requestId=null,requestAmount=null;
  const cardState=new Map();
  let filters={},loadSequence=0;
  function state(id){if(!cardState.has(String(id)))cardState.set(String(id),{index:0,amount:null,pending:false,message:''});return cardState.get(String(id));}
  function gallery(a){const images=a.images?.length?a.images:a.cover_image?[{image_url:a.cover_image}]:[];return `<div class="card-gallery" data-gallery="${esc(a.id)}" tabindex="0" aria-label="Bike photos — swipe to browse">${images.length?images.map((img,i)=>`<div class="gallery-slide"><img src="${esc(img.image_url)}" alt="${esc(a.brand)} ${esc(a.model)} — photo ${i+1}" loading="lazy"></div>`).join(''):'<div class="gallery-slide photo-missing">No photo available</div>'}</div>${images.length>1?`<div class="gallery-controls"><button type="button" data-photo="${esc(a.id)}" data-direction="-1" aria-label="Previous photo">←</button><span>${images.length} photos · Swipe to browse</span><button type="button" data-photo="${esc(a.id)}" data-direction="1" aria-label="Next photo">→</button></div>`:''}`;}
  function dealerCard(a){const st=state(a.id),minimum=a.minimum_bid??(a.highest_bid==null?Number(a.starting_price):Number(a.highest_bid)+Number(a.min_increment));return `<article class="lot-card">${gallery(a)}<span class="lot-phase">LOT #${esc(a.id)} · ${esc(a.phase)}</span><h3>${esc(a.brand)} ${esc(a.model)}</h3><p>${esc(a.year)} · ${esc(a.kilometers_driven??'—')} km · ${esc(a.registration_number||'Bike #'+a.bike_id)}</p><div class="card-bid-stats"><div><small>${a.highest_bid==null?'Starting price':'Highest bid'}</small><strong>${rupees(a.highest_bid??a.starting_price)}</strong></div><div><small>Your bid</small><strong>${a.my_bid==null?'—':rupees(a.my_bid)}</strong></div></div><p>${esc(a.bid_count)} bids${a.is_winner?' · You won':a.is_leading?' · You lead':a.my_bid!=null&&a.phase==='live'?' · Outbid':''}</p><div class="lot-timer">${timer(a)}</div>${a.phase==='live'&&currentUser?.role!=='admin'?`<form data-inline-bid="${esc(a.id)}"><label for="amount-${esc(a.id)}">Your bid amount (₹)</label><div class="quick-bids">${[1,2,5].map(n=>`<button type="button" data-increase="${esc(a.id)}" data-multiple="${n}" ${st.pending?'disabled':''}>+${rupees(Number(a.min_increment)*n)}</button>`).join('')}</div><div class="inline-bid-controls"><button type="button" data-increase="${esc(a.id)}" data-multiple="-1" aria-label="Decrease bid" ${st.pending?'disabled':''}>−</button><input id="amount-${esc(a.id)}" data-inline-amount="${esc(a.id)}" name="amount" type="number" min="${esc(minimum)}" max="1000000000" step="1" required value="${esc(st.amount??minimum)}" ${st.pending?'disabled':''}><button type="button" data-increase="${esc(a.id)}" data-multiple="1" aria-label="Increase bid" ${st.pending?'disabled':''}>+</button><button type="submit" ${st.pending?'disabled':''}>${st.pending?'Submitting…':'Bid Now'}</button></div><small>Minimum bid ${rupees(minimum)}</small></form>`:''}<p class="card-message" role="status">${esc(st.message)}</p><button type="button" data-lot="${esc(a.id)}">View bike details →</button></article>`;}
  async function refresh(){const res=await fetch('/api/auth/refresh',{method:'POST',credentials:'include'});if(!res.ok)return false;const data=await res.json();token=data.accessToken;return Boolean(token);}
  function signedOut(message='Please log in to view auctions.'){document.body?.classList.remove('dealer-mode');if($('dealerHeading'))$('dealerHeading').textContent='Bid on quality used bikes.';if($('dealerIntro'))$('dealerIntro').textContent='Log in to review bike details, follow the timer and place your bid.';token=null;currentUser=null;loadSequence++;cardState.clear();$('dealerLogin').hidden=false;$('dealerSession').hidden=true;$('dealerAuctions').innerHTML='';$('dealerMsg').textContent=message;$('lotDialog').close();}
  async function api(url,opts={}){const headers=new Headers(opts.headers||{});const send=()=>{headers.set('Authorization','Bearer '+token);return fetch(url,{...opts,headers,credentials:'include'});};let res=await send();if(res.status===401){if(!refreshing)refreshing=refresh().finally(()=>refreshing=null);if(await refreshing)res=await send();else signedOut('Session expired. Please log in again.');}return json(res);}
  function render(){const active=document.activeElement?.dataset?.inlineAmount;$('dealerAuctions').innerHTML=rows.map(a=>card(a)).join('')||'<p class="lot-empty">No auctions match this view.</p>';document.querySelectorAll('[data-gallery]').forEach(el=>{el.scrollLeft=state(el.dataset.gallery).index*el.clientWidth;});if(active)$('amount-'+active)?.focus?.({preventScroll:true});tick();}
  async function load(){const sequence=++loadSequence,params=new URLSearchParams({page,phase,...filters});const data=await api('/api/auctions?'+params);if(sequence!==loadSequence||!token)return;rows=data.rows;sync(data.serverNow);render();pager('dealer',page,data.total);}
  if($('auctionSearch'))$('auctionSearch').onsubmit=e=>{e.preventDefault();filters=Object.fromEntries([...new FormData(e.currentTarget)].filter(([,v])=>String(v).trim()));page=1;load().catch(e=>$('dealerMsg').textContent=e.message);};
  if($('clearAuctionSearch'))$('clearAuctionSearch').onclick=()=>{$('auctionSearch').reset();filters={};page=1;load().catch(e=>$('dealerMsg').textContent=e.message);};
  async function signedIn(user){currentUser=user;phase='live';page=1;document.body?.classList.add('dealer-mode');document.querySelectorAll('[data-phase]').forEach(el=>el.setAttribute('aria-pressed',String(el.dataset.phase==='live')));if($('dealerHeading'))$('dealerHeading').textContent='Running auctions';if($('dealerIntro'))$('dealerIntro').textContent='Follow live prices and countdowns. Select a bike to review its details and bid.';$('dealerLogin').hidden=true;$('dealerSession').hidden=false;$('dealerName').textContent=(user.full_name||user.email)+' · '+user.role;$('dealerMsg').textContent='Bids are binding. Review the bike and price before submitting.';await load();$('live').scrollIntoView?.({behavior:'smooth',block:'start'});}
  $('dealerLogin').onsubmit=async e=>{e.preventDefault();const form=e.currentTarget,button=e.submitter||form.querySelector('button[type="submit"]');button.disabled=true;$('dealerMsg').textContent='Signing in…';try{const data=await json(await fetch('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},credentials:'include',body:JSON.stringify(Object.fromEntries(new FormData(form)))}));token=data.accessToken;form.reset();await signedIn(data.user);}catch(err){$('dealerMsg').textContent=err.message;}finally{button.disabled=false;}};
  $('dealerLogout').onclick=async()=>{await fetch('/api/auth/logout',{method:'POST',credentials:'include'}).catch(()=>{});signedOut('Logged out.');};
  $('dealerRegister').onsubmit=async e=>{e.preventDefault();const form=e.currentTarget,b=e.submitter||form.querySelector('button[type="submit"]');b.disabled=true;try{const body={...Object.fromEntries(new FormData(form)),role:'dealer'};const data=await json(await fetch('/api/auth/register',{method:'POST',headers:{'Content-Type':'application/json'},credentials:'include',body:JSON.stringify(body)}));$('registerMsg').textContent=data.message;form.reset();}catch(err){$('registerMsg').textContent=err.message;}finally{b.disabled=false;}};
  document.querySelectorAll('[data-phase]').forEach(b=>b.onclick=()=>{phase=b.dataset.phase;document.querySelectorAll('[data-phase]').forEach(el=>el.setAttribute('aria-pressed',String(el===b)));page=1;load().catch(e=>$('dealerMsg').textContent=e.message);});
  document.querySelectorAll('a[href="#upcoming"]').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();phase='upcoming';document.querySelectorAll('[data-phase]').forEach(el=>el.setAttribute('aria-pressed',String(el.dataset.phase===phase)));page=1;load().catch(e=>$('dealerMsg').textContent=e.message);$('live').scrollIntoView({behavior:'smooth'});}));
  for(const [id,delta] of [['dealerPrev',-1],['dealerNext',1]])$(id).onclick=()=>{page+=delta;load().catch(e=>$('dealerMsg').textContent=e.message);};
  async function details(id,initial=false){const data=await api('/api/auctions/'+id);if(selected!==id)return;const a=data.auction,b=data.bike;sync(data.serverNow);$('lotDetail').innerHTML=`<h2>${esc(b.brand)} ${esc(b.model)}</h2><div class="lot-photos">${b.images.map(img=>`<img src="${esc(img.image_url)}" alt="Bike photo">`).join('')}</div><p>${esc(b.year)} · ${b.kilometers_driven==null?'KM not recorded':esc(b.kilometers_driven)+' km'} · Ownership ${esc(b.ownership_count??'not recorded')} · ${esc(b.fuel_type)}</p><p>${esc(b.condition_notes||'No condition notes recorded.')}</p><span class="lot-phase">${esc(a.phase)}</span><p class="lot-price">${rupees(a.highest_bid??a.starting_price)}</p><div class="lot-timer">${timer(a)}</div><p>${a.is_winner?'You won. Contact BikesKart to arrange payment and handover.':a.is_leading&&a.phase==='live'?'You are the leading bidder.':a.status==='closed'?a.result==='sold'?'Winning bid confirmed.':'Auction ended without a winner.':''}</p><p>Starts: ${esc(when(a.starts_at))}<br>Ends: ${esc(when(a.ends_at))}<br>Minimum increase: ${rupees(a.min_increment)}</p><h3>Recent bids</h3><ol>${data.bids.map(bid=>`<li>${rupees(bid.amount)} · ${esc(when(bid.created_at))}</li>`).join('')||'<li>No bids yet.</li>'}</ol>`;$('bidForm').hidden=a.phase!=='live'||currentUser?.role==='admin';$('bidAmount').min=a.minimum_bid;if(initial){$('bidAmount').value=a.minimum_bid;$('bidMsg').textContent='Minimum bid: '+rupees(a.minimum_bid);requestId=null;requestAmount=null;}tick();}
  $('dealerAuctions').onclick=async e=>{const photo=e.target.closest('[data-photo]');if(photo){const el=document.querySelector('[data-gallery="'+photo.dataset.photo+'"]');if(el){const st=state(photo.dataset.photo);st.index=Math.max(0,Math.min(el.children.length-1,st.index+Number(photo.dataset.direction)));el.scrollTo({left:st.index*el.clientWidth,behavior:'smooth'});}return;}const increase=e.target.closest('[data-increase]');if(increase){const a=rows.find(a=>String(a.id)===increase.dataset.increase),input=$('amount-'+increase.dataset.increase);if(a&&input){input.value=Math.max(Number(input.min),Math.min(1000000000,Number(input.value)+Number(a.min_increment)*Number(increase.dataset.multiple)));state(a.id).amount=input.value;}return;}const b=e.target.closest('[data-lot]');if(!b)return;selected=b.dataset.lot;try{await details(selected,true);$('lotDialog').showModal();}catch(err){$('dealerMsg').textContent=err.message;}};
  $('dealerAuctions').addEventListener('input',e=>{if(e.target.dataset.inlineAmount)state(e.target.dataset.inlineAmount).amount=e.target.value;});
  $('dealerAuctions').addEventListener('scroll',e=>{if(e.target.dataset?.gallery&&e.target.clientWidth)state(e.target.dataset.gallery).index=Math.round(e.target.scrollLeft/e.target.clientWidth);},true);
  $('dealerAuctions').addEventListener('error',e=>{if(e.target.tagName==='IMG'){const slide=e.target.closest('.gallery-slide');if(slide){slide.textContent='Photo unavailable';slide.classList.add('photo-missing');}}},true);
  $('dealerAuctions').addEventListener('submit',async e=>{const form=e.target;if(!form.dataset.inlineBid)return;e.preventDefault();const id=form.dataset.inlineBid,st=state(id);if(st.pending)return;const amount=form.elements.amount.value;st.amount=amount;if(!st.requestId||st.requestAmount!==amount){st.requestId=crypto.randomUUID();st.requestAmount=amount;}st.pending=true;st.message='Submitting bid…';render();try{const data=await api(`/api/auctions/${id}/bids`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({amount,requestId:st.requestId})});st.message='Bid accepted: '+rupees(data.amount);st.requestId=null;st.amount=null;await load();}catch(err){st.message=err.message;}finally{st.pending=false;render();}});
  $('closeLot').onclick=()=>$('lotDialog').close();$('lotDialog').addEventListener('close',()=>{selected=null;requestId=null;});
  $('bidForm').onsubmit=async e=>{e.preventDefault();if(submitting||!selected)return;const id=selected,amount=$('bidAmount').value,button=e.submitter||e.currentTarget.querySelector('button[type="submit"]');submitting=true;button.disabled=true;$('bidMsg').textContent='Submitting bid…';if(!requestId||amount!==requestAmount){requestId=crypto.randomUUID();requestAmount=amount;}try{const data=await api(`/api/auctions/${id}/bids`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({amount,requestId})});$('bidMsg').textContent='Bid accepted: '+rupees(data.amount);requestId=null;requestAmount=null;await details(id);await load();}catch(err){$('bidMsg').textContent=err.message;try{await details(id);}catch{}}finally{submitting=false;button.disabled=false;}};
  setInterval(async()=>{if(!token||busy||document.hidden)return;busy=true;try{await load();if(selected&&$('lotDialog').open&&!submitting)await details(selected);}catch(err){$('dealerMsg').textContent=err.message;}finally{busy=false;}},5000);
  (async()=>{try{if(await refresh()){const data=await api('/api/auth/me');await signedIn(data.user);}}catch(err){signedOut(err.message);}})();
})();
