(() => {
  const $ = id => document.getElementById(id);
  const esc = value => String(value ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const rupees = value => new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(Number(value));
  const when = value => new Date(value).toLocaleString('en-IN');
  let offset = 0;
  function sync(serverNow) {offset=new Date(serverNow).getTime()-Date.now();}
  function timer(a) {
    if(a.phase==='ended'||a.phase==='cancelled') return a.phase==='cancelled'?'Cancelled':'Ended';
    const target=a.phase==='upcoming'?a.starts_at:a.ends_at;
    return `<span data-deadline="${esc(target)}" data-start="${a.phase==='upcoming'}"></span>`;
  }
  function tick() {
    document.querySelectorAll('[data-deadline]').forEach(el=>{
      const seconds=Math.max(0,Math.ceil((new Date(el.dataset.deadline).getTime()-Date.now()-offset)/1000));
      el.textContent=seconds===0?'Updating status…':`${el.dataset.start==='true'?'Starts in':'Ends in'} ${Math.floor(seconds/3600)}h ${Math.floor(seconds%3600/60)}m ${seconds%60}s`;
    });
  }
  function card(a,admin=false) {
    return `<article class="lot-card">${a.cover_image?`<img src="${esc(a.cover_image)}" alt="${esc(a.brand)} ${esc(a.model)}" loading="lazy">`:''}<span class="lot-phase">LOT #${esc(a.id)} · ${esc(a.phase)}</span><h3>${esc(a.brand)} ${esc(a.model)}</h3><p>${esc(a.year)} · ${a.kilometers_driven==null?'KM not recorded':esc(a.kilometers_driven)+' km'} · Bike #${esc(a.bike_id)}</p><div class="lot-price">${rupees(a.highest_bid??a.starting_price)}</div><p>${a.highest_bid==null?'Starting price':esc(a.bid_count)+' bids'}${a.is_leading?' · You lead':''}${a.is_winner?' · You won':''}</p><div class="lot-timer">${timer(a)}</div><p>${a.status==='closed'?a.result==='sold'?'Winning bid confirmed':'No winner — reserve not met':''}</p>${admin?`<p>Starts ${esc(when(a.starts_at))}<br>Ends ${esc(when(a.ends_at))}<br>Reserve ${rupees(a.reserve_price)}</p>${a.winner_name?`<p>Winner: ${esc(a.winner_name)}<br>${esc(a.winner_email)}<br>Arrange payment and handover.</p>`:''}${a.status==='open'&&Number(a.bid_count)===0?`<button type="button" data-cancel="${esc(a.id)}">Cancel auction</button>`:''}`:`<button type="button" data-lot="${esc(a.id)}">VIEW BIKE${a.phase==='live'?' & BID':''} →</button>`}</article>`;
  }
  async function json(res) {const data=await res.json().catch(()=>({}));if(!res.ok)throw new Error(data.error||'Request failed');return data;}
  function pager(prefix,page,total) {$(prefix+'Prev').disabled=page===1;$(prefix+'Next').disabled=page*50>=Number(total);$(prefix+'Page').textContent=`Page ${page} of ${Math.max(1,Math.ceil(total/50))}`;}
  setInterval(tick,1000);
  if($('auctionForm')) {
    let ready=false,page=1,accountPage=1,loading=false;
    const api=(url,opts)=>window.bkAdminApi(url,opts).then(json);
    function defaults(){for(const [key,delta] of [['startsAt',300000],['endsAt',3900000]]){const date=new Date(Date.now()+delta);date.setMinutes(date.getMinutes()-date.getTimezoneOffset());$('auctionForm').elements[key].value=date.toISOString().slice(0,16);}}
    defaults();
    async function loadAuctions(){const data=await api('/api/auctions?page='+page);sync(data.serverNow);$('adminAuctions').innerHTML=data.rows.map(a=>card(a,true)).join('')||'<p class="lot-empty">No auctions scheduled yet.</p>';pager('admin',page,data.total);tick();}
    async function loadAccounts(){const data=await api('/api/admin/accounts?page='+accountPage);$('accountList').innerHTML=data.rows.map(u=>`<div class="account-row"><div><strong>${esc(u.full_name)}</strong><small>${esc(u.email)} · ${esc(u.role)}</small><small>${u.is_verified?'Approved':'Pending approval'} · ${u.is_active?'Active':'Disabled'}</small></div><div>${!u.is_verified?`<button type="button" data-account="${esc(u.id)}" data-field="is_verified" data-value="true">Approve</button>`:''}<button type="button" data-account="${esc(u.id)}" data-field="is_active" data-value="${!u.is_active}">${u.is_active?'Disable':'Enable'}</button></div></div>`).join('')||'<p>No dealer accounts yet.</p>';pager('account',accountPage,data.total);}
    window.addEventListener('bk-admin-ready',async()=>{ready=true;try{await Promise.all([loadAuctions(),loadAccounts()]);const data=await api('/api/admin/bikes?pageSize=50');$('bikeOptions').innerHTML=data.rows.map(b=>`<option value="${esc(b.id)}">${esc(b.brand)} ${esc(b.model)} (${esc(b.status)})</option>`).join('');}catch(e){$('auctionAdminMsg').textContent=e.message;}});
    $('auctionForm').addEventListener('submit',async e=>{e.preventDefault();const form=e.currentTarget,button=e.submitter||form.querySelector('button[type="submit"]');button.disabled=true;$('auctionAdminMsg').textContent='Scheduling…';try{const body=Object.fromEntries(new FormData(form));body.startsAt=new Date(body.startsAt).toISOString();body.endsAt=new Date(body.endsAt).toISOString();const data=await api('/api/auctions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});$('auctionAdminMsg').textContent=`Auction #${data.auction.id} scheduled.`;form.reset();defaults();page=1;await loadAuctions();}catch(err){$('auctionAdminMsg').textContent=err.message;}finally{button.disabled=false;}});
    $('adminAuctions').addEventListener('click',async e=>{const button=e.target.closest('[data-cancel]');if(!button)return;button.disabled=true;try{await api(`/api/auctions/${button.dataset.cancel}/cancel`,{method:'POST'});await loadAuctions();$('auctionAdminMsg').textContent='Auction cancelled.';}catch(err){$('auctionAdminMsg').textContent=err.message;button.disabled=false;}});
    $('accountList').addEventListener('click',async e=>{const b=e.target.closest('[data-account]');if(!b)return;b.disabled=true;try{await api('/api/admin/accounts/'+b.dataset.account,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({[b.dataset.field]:b.dataset.value==='true'})});await loadAccounts();$('accountMsg').textContent='Account updated.';}catch(err){$('accountMsg').textContent=err.message;b.disabled=false;}});
    for(const [id,delta,accounts] of [['adminPrev',-1,false],['adminNext',1,false],['accountPrev',-1,true],['accountNext',1,true]])$(id).onclick=()=>{if(accounts)accountPage+=delta;else page+=delta;(accounts?loadAccounts():loadAuctions()).catch(e=>{$('auctionAdminMsg').textContent=e.message;});};
    setInterval(async()=>{if(!ready||loading||document.hidden||!$('dashboardPanel').classList.contains('active'))return;loading=true;try{await loadAuctions();}catch(e){$('auctionAdminMsg').textContent=e.message;}finally{loading=false;}},5000);
    return;
  }
  if(!$('dealerLogin'))return;
  let token=null,refreshing=null,currentUser=null,phase='live',rows=[],page=1,selected=null,busy=false,submitting=false,requestId=null,requestAmount=null;
  async function refresh(){const res=await fetch('/api/auth/refresh',{method:'POST',credentials:'include'});if(!res.ok)return false;const data=await res.json();token=data.accessToken;return Boolean(token);}
  function signedOut(message='Please log in to view auctions.'){token=null;currentUser=null;$('dealerLogin').hidden=false;$('dealerSession').hidden=true;$('dealerAuctions').innerHTML='';$('dealerMsg').textContent=message;$('lotDialog').close();}
  async function api(url,opts={}){const headers=new Headers(opts.headers||{});const send=()=>{headers.set('Authorization','Bearer '+token);return fetch(url,{...opts,headers,credentials:'include'});};let res=await send();if(res.status===401){if(!refreshing)refreshing=refresh().finally(()=>refreshing=null);if(await refreshing)res=await send();else signedOut('Session expired. Please log in again.');}return json(res);}
  function render(){const matching=rows.filter(a=>a.phase===phase||(phase==='ended'&&a.phase==='cancelled'));$('dealerAuctions').innerHTML=matching.map(a=>card(a)).join('')||'<p class="lot-empty">No '+esc(phase)+' auctions on this page.</p>';tick();}
  async function load(){const data=await api('/api/auctions?page='+page);rows=data.rows;sync(data.serverNow);render();pager('dealer',page,data.total);}
  async function signedIn(user){currentUser=user;$('dealerLogin').hidden=true;$('dealerSession').hidden=false;$('dealerName').textContent=(user.full_name||user.email)+' · '+user.role;$('dealerMsg').textContent='Bids are binding. Review the bike and price before submitting.';await load();}
  $('dealerLogin').onsubmit=async e=>{e.preventDefault();const form=e.currentTarget,button=e.submitter||form.querySelector('button[type="submit"]');button.disabled=true;$('dealerMsg').textContent='Signing in…';try{const data=await json(await fetch('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},credentials:'include',body:JSON.stringify(Object.fromEntries(new FormData(form)))}));token=data.accessToken;form.reset();await signedIn(data.user);}catch(err){$('dealerMsg').textContent=err.message;}finally{button.disabled=false;}};
  $('dealerLogout').onclick=async()=>{await fetch('/api/auth/logout',{method:'POST',credentials:'include'}).catch(()=>{});signedOut('Logged out.');};
  $('dealerRegister').onsubmit=async e=>{e.preventDefault();const form=e.currentTarget,b=e.submitter||form.querySelector('button[type="submit"]');b.disabled=true;try{const body={...Object.fromEntries(new FormData(form)),role:'dealer'};const data=await json(await fetch('/api/auth/register',{method:'POST',headers:{'Content-Type':'application/json'},credentials:'include',body:JSON.stringify(body)}));$('registerMsg').textContent=data.message;form.reset();}catch(err){$('registerMsg').textContent=err.message;}finally{b.disabled=false;}};
  document.querySelectorAll('[data-phase]').forEach(b=>b.onclick=()=>{phase=b.dataset.phase;document.querySelectorAll('[data-phase]').forEach(el=>el.setAttribute('aria-pressed',String(el===b)));render();});
  document.querySelectorAll('a[href="#upcoming"]').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();phase='upcoming';document.querySelectorAll('[data-phase]').forEach(el=>el.setAttribute('aria-pressed',String(el.dataset.phase===phase)));render();$('live').scrollIntoView({behavior:'smooth'});}));
  for(const [id,delta] of [['dealerPrev',-1],['dealerNext',1]])$(id).onclick=()=>{page+=delta;load().catch(e=>$('dealerMsg').textContent=e.message);};
  async function details(id,initial=false){const data=await api('/api/auctions/'+id);if(selected!==id)return;const a=data.auction,b=data.bike;sync(data.serverNow);$('lotDetail').innerHTML=`<h2>${esc(b.brand)} ${esc(b.model)}</h2><div class="lot-photos">${b.images.map(img=>`<img src="${esc(img.image_url)}" alt="Bike photo">`).join('')}</div><p>${esc(b.year)} · ${b.kilometers_driven==null?'KM not recorded':esc(b.kilometers_driven)+' km'} · Ownership ${esc(b.ownership_count??'not recorded')} · ${esc(b.fuel_type)}</p><p>${esc(b.condition_notes||'No condition notes recorded.')}</p><span class="lot-phase">${esc(a.phase)}</span><p class="lot-price">${rupees(a.highest_bid??a.starting_price)}</p><div class="lot-timer">${timer(a)}</div><p>${a.is_winner?'You won. Contact BikesKart to arrange payment and handover.':a.is_leading&&a.phase==='live'?'You are the leading bidder.':a.status==='closed'?a.result==='sold'?'Winning bid confirmed.':'Auction ended without a winner.':''}</p><p>Starts: ${esc(when(a.starts_at))}<br>Ends: ${esc(when(a.ends_at))}<br>Minimum increase: ${rupees(a.min_increment)}</p><h3>Recent bids</h3><ol>${data.bids.map(bid=>`<li>${rupees(bid.amount)} · ${esc(when(bid.created_at))}</li>`).join('')||'<li>No bids yet.</li>'}</ol>`;$('bidForm').hidden=a.phase!=='live'||currentUser?.role==='admin';$('bidAmount').min=a.minimum_bid;if(initial){$('bidAmount').value=a.minimum_bid;$('bidMsg').textContent='Minimum bid: '+rupees(a.minimum_bid);requestId=null;requestAmount=null;}tick();}
  $('dealerAuctions').onclick=async e=>{const b=e.target.closest('[data-lot]');if(!b)return;selected=b.dataset.lot;try{await details(selected,true);$('lotDialog').showModal();}catch(err){$('dealerMsg').textContent=err.message;}};
  $('closeLot').onclick=()=>$('lotDialog').close();$('lotDialog').addEventListener('close',()=>{selected=null;requestId=null;});
  $('bidForm').onsubmit=async e=>{e.preventDefault();if(submitting||!selected)return;const id=selected,amount=$('bidAmount').value,button=e.submitter||e.currentTarget.querySelector('button[type="submit"]');submitting=true;button.disabled=true;$('bidMsg').textContent='Submitting bid…';if(!requestId||amount!==requestAmount){requestId=crypto.randomUUID();requestAmount=amount;}try{const data=await api(`/api/auctions/${id}/bids`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({amount,requestId})});$('bidMsg').textContent='Bid accepted: '+rupees(data.amount);requestId=null;requestAmount=null;await details(id);await load();}catch(err){$('bidMsg').textContent=err.message;try{await details(id);}catch{}}finally{submitting=false;button.disabled=false;}};
  setInterval(async()=>{if(!token||busy||document.hidden)return;busy=true;try{await load();if(selected&&$('lotDialog').open&&!submitting)await details(selected);}catch(err){$('dealerMsg').textContent=err.message;}finally{busy=false;}},5000);
  (async()=>{try{if(await refresh()){const data=await api('/api/auth/me');await signedIn(data.user);}}catch(err){signedOut(err.message);}})();
})();
