(() => {
 const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let token=null,page=1,current=null,stream=null,loadingPhoto=false;
 const baseFields={customer_name:['Customer name','text'],customer_phone:['Mobile','tel'],customer_email:['Email','email'],customer_address:['Address','text'],customer_kycType:['KYC document type','text'],brand:['Brand','text'],model:['Model','text'],year:['Manufacturing year','number'],registrationNumber:['Registration number','text'],registrationDate:['Registration date','date'],engineNumber:['Engine number','text'],chassisNumber:['Chassis number','text'],kilometersDriven:['Odometer (km)','number'],ownershipCount:['Number of owners','number'],fuelType:['Fuel type','text'],conditionNotes:['Vehicle description','text'],inspectionNotes:['Inspection observations','text'],location:['Inspection address / location','text'],inspectionAt:['Inspection date & time','datetime-local']};
 const profile={registrationYear:['Registration year','number'],hpStatus:['HP status',['Yes','No']],nocStatus:['NOC available',['Yes','No']],rcAvailable:['RC available',['Yes','No']],keysCount:['Keys','number'],insuranceStatus:['Insurance',['Valid','Invalid']],engineNoise:['Engine noise',['Yes','No']],smoke:['Smoke',['Yes','No']],selfStart:['Self start',['Yes','No']],clutchPlate:['Clutch plate',['Good','Average','Poor']],timingChainNoise:['Timing chain noise',['Yes','No']],engineCondition:['Engine condition',['Good','Average','Poor']],batteryWorking:['Battery working',['Yes','No']],chassis:['Chassis',['Good','Average','Poor']],bodyLine:['Body condition',['Good','Average','Poor']],vehicleRating:['Rating (1–5)','number']};
 const chargeFields={fineCost:'Notice / traffic fine',paintingCost:'Painting',damageCost:'Other damage repairs',oilChangeCost:'Oil change (mandatory entry)',seatChangeCost:'Seat change (mandatory entry)',brakePadCost:'Brake pad change (mandatory entry)'};
 function partRow(part={}){return `<div class="part-row actions"><input data-part-name placeholder="Replacement part name" value="${esc(part.name)}" maxlength="150"><input data-part-cost type="number" min="0" step="0.01" placeholder="Cost ₹" value="${esc(part.cost)}"><button type="button" data-remove-part>Remove</button></div>`;}
 function chargeEditor(c={}){return `<section><h3>Notice, fines & inspection charges</h3><p>Enter each charge in rupees; use 0 if there is no charge. List additional replacement parts separately. Do not repeat oil, seat or brake pad costs in the parts list.</p><div class="grid">${Object.entries(chargeFields).map(([key,label])=>`<label>${label} (₹)<input name="charge_${key}" type="number" min="0" step="0.01" value="${esc(c[key])}"></label>`).join('')}${['fineDetails','paintingDetails','damageDetails'].map((key,i)=>`<label>${['Notice / fine details','Painting work required','Other damages / repairs'][i]}<textarea name="charge_${key}" maxlength="3000">${esc(c[key])}</textarea></label>`).join('')}<label>Transport (₹)<input value="1000" readonly></label></div><h4>Additional replacement parts</h4><div id="inspectionParts">${(c.parts||[]).map(partRow).join('')}</div><button type="button" id="addInspectionPart">Add replacement part</button><p><strong id="inspectionChargeTotal"></strong></p></section>`;}
 function collectCharges(){const form=$('executiveInspectionForm'),c={transportCost:'1000',parts:[]};for(const k of [...Object.keys(chargeFields),'fineDetails','paintingDetails','damageDetails'])c[k]=form.elements['charge_'+k].value;for(const row of form.querySelectorAll('.part-row'))c.parts.push({name:row.querySelector('[data-part-name]').value,cost:row.querySelector('[data-part-cost]').value});return c;}
 function updateChargesTotal(){const c=collectCharges(),values=[...Object.keys(chargeFields).map(k=>c[k]),...c.parts.map(p=>p.cost)];const paise=100000+values.reduce((sum,v)=>sum+(Number.isFinite(Number(v))?Math.round(Number(v)*100):0),0);$('inspectionChargeTotal').textContent='Total estimated charges: '+new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR'}).format(paise/100);}
 $('executiveInspectionForm').addEventListener('input',e=>{if(e.target.name?.startsWith('charge_')||e.target.closest('.part-row'))updateChargesTotal();});
 $('executiveInspectionForm').addEventListener('click',e=>{if(e.target.id==='addInspectionPart'){if($('inspectionParts').children.length>=30)return;$('inspectionParts').insertAdjacentHTML('beforeend',partRow());}if(e.target.hasAttribute('data-remove-part'))e.target.closest('.part-row').remove();updateChargesTotal();});
 function inspectionStatus(status){return {draft:'Not assigned',assigned:'Inspection pending',submitted:'Inspection completed — awaiting admin review',approved:'Inspection completed — approved and sent to inventory'}[status]||status;}
 async function refresh(){const r=await fetch('/api/auth/refresh',{method:'POST',credentials:'include'});if(!r.ok)return false;token=(await r.json()).accessToken;return !!token;}
 async function api(url,options={}){const headers=new Headers(options.headers||{});headers.set('Authorization','Bearer '+token);let r=await fetch(url,{...options,headers,credentials:'include'});if(r.status===401&&await refresh()){headers.set('Authorization','Bearer '+token);r=await fetch(url,{...options,headers,credentials:'include'});}if(!r.ok){const d=await r.json().catch(()=>({}));throw Error(d.error||'Could not complete request');}return r;}
 async function data(url,opts){return (await api(url,opts)).json();}
 function stopCamera(){stream?.getTracks().forEach(t=>t.stop());stream=null;$('inspectionCamera').srcObject=null;$('inspectionCamera').hidden=true;$('cameraCapture').hidden=true;$('cameraStop').hidden=true;}
 function signedOut(){stopCamera();token=null;current=null;$('executiveTask').hidden=true;$('executiveJobs').hidden=true;$('executiveLogin').hidden=false;$('executiveLogout').hidden=true;$('executiveJobList').innerHTML='';$('executiveFiles').innerHTML='';$('executiveFields').innerHTML='';}
 async function signedIn(user){if(user.role!=='executive')throw Error('Use an executive account for this page');$('executiveName').textContent=user.full_name||user.email;$('executiveLogin').hidden=true;$('executiveJobs').hidden=false;$('executiveLogout').hidden=false;await jobs();}
 async function jobs(){const d=await data('/api/purchases?page='+page);$('executiveJobList').innerHTML=d.rows.map(r=>`<article class="job"><h2>${esc(r.vehicle.brand||'Bike')} ${esc(r.vehicle.model||'Inspection')}</h2><p>${esc(r.vehicle.registrationNumber||'Registration to be recorded')} · ${esc(inspectionStatus(r.status))}</p><p>${esc(r.customer.name)} · ${esc(r.customer.phone)}<br>${esc(r.vehicle.inspectionZone||'Zone not recorded')} Bengaluru · ${esc(r.location||'Location to be recorded')}</p><button type="button" data-task="${r.id}">Open inspection</button></article>`).join('')||'<p>No inspections assigned yet.</p>';$('executivePage').textContent=`Page ${page}`;$('executivePrev').disabled=page===1;$('executiveNext').disabled=page*30>=d.total;}
 function input(key,label,type,value){if(Array.isArray(type))return `<label>${label}<select name="${key}"><option value="">Not recorded</option>${type.map(v=>`<option ${v===value?'selected':''}>${esc(v)}</option>`).join('')}</select></label>`;return `<label>${label}<input name="${key}" type="${type}" value="${esc(value)}" ${type==='number'?'min="0" step="1"':''}></label>`;}
 function localTime(value){if(!value)return '';const d=new Date(value.includes('T')?value:value.replace(' ','T')+'Z');d.setMinutes(d.getMinutes()-d.getTimezoneOffset());return d.toISOString().slice(0,16);}
 async function task(id){stopCamera();const d=await data('/api/purchases/'+id);current=d.purchase;$('executiveJobs').hidden=true;$('executiveTask').hidden=false;$('executiveTaskTitle').textContent=(current.vehicle.registrationNumber||'Bike inspection');let call=$('executiveCustomerCall');if(call)call.remove();call=document.createElement('a');call.id='executiveCustomerCall';call.href='tel:'+current.customer.phone.replace(/[^+0-9]/g,'');call.textContent='Call customer: '+current.customer.phone;$('executiveTaskMeta').after(call);$('executiveTaskMeta').textContent='Status: '+inspectionStatus(current.status)+' · Bengaluru '+(current.vehicle.inspectionZone||'Zone not recorded');$('executiveFields').innerHTML=Object.entries(baseFields).map(([k,[label,type]])=>input(k,label,type,k.startsWith('customer_')?current.customer[k.slice(9)]:k==='location'?current.location:k==='inspectionAt'?localTime(current.inspection_at):current.vehicle[k])).join('')+Object.entries(profile).map(([k,[label,type]])=>input('profile_'+k,label,type,current.vehicle.detailProfile?.[k])).join('')+chargeEditor(current.vehicle.inspectionCharges);updateChargesTotal();const editable=current.status==='assigned';$('executiveInspectionForm').querySelectorAll('input,select,textarea,button').forEach(el=>el.disabled=!editable);$('cameraPanel').hidden=!editable;$('executiveDocumentForm').hidden=!editable;$('executiveSubmit').hidden=!editable;$('executiveFiles').innerHTML='<h3>Saved photos and documents</h3>'+d.documents.map(doc=>`<p><button type="button" data-document="${doc.id}">${esc(doc.kind)} · ${esc(doc.created_at)}${doc.capture_source?' · Camera':''}</button></p>`).join('');}
 $('executiveLoginForm').addEventListener('submit',async e=>{e.preventDefault();try{const r=await fetch('/api/auth/login',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(new FormData(e.target)))}),d=await r.json();if(!r.ok)throw Error(d.error||'Login failed');token=d.accessToken;await signedIn(d.user);e.target.reset();}catch(err){signedOut();$('executiveLoginMsg').textContent=err.message;}});
 $('executiveLogout').onclick=async()=>{await fetch('/api/auth/logout',{method:'POST',credentials:'include'});signedOut();};$('executiveBack').onclick=async()=>{stopCamera();$('executiveTask').hidden=true;$('executiveJobs').hidden=false;await jobs();};$('executivePrev').onclick=()=>{page--;jobs().catch(e=>$('executiveLoginMsg').textContent=e.message);};$('executiveNext').onclick=()=>{page++;jobs().catch(e=>$('executiveLoginMsg').textContent=e.message);};$('executiveJobList').onclick=e=>{const b=e.target.closest('[data-task]');if(b)task(b.dataset.task).catch(e=>$('executiveLoginMsg').textContent=e.message);};
 $('executiveInspectionForm').onsubmit=async e=>{e.preventDefault();const customer={},vehicle={detailProfile:{}},form=e.target,body={version:current.version};for(const k of Object.keys(baseFields)){const value=form.elements[k].value;if(k.startsWith('customer_'))customer[k.slice(9)]=value;else if(k==='location')body.location=value;else if(k==='inspectionAt')body.inspectionAt=value?new Date(value).toISOString():null;else vehicle[k]=value;}for(const k of Object.keys(profile))vehicle.detailProfile[k]=form.elements['profile_'+k].value;if(current.vehicle.latitude!=null){vehicle.latitude=current.vehicle.latitude;vehicle.longitude=current.vehicle.longitude;}vehicle.inspectionCharges=collectCharges();body.customer=customer;body.vehicle=vehicle;try{await data('/api/purchases/'+current.id,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});await task(current.id);$('executiveTaskMsg').textContent='Inspection saved.';}catch(err){$('executiveTaskMsg').textContent=err.message;}};
 $('executiveLocate').onclick=()=>{if(!navigator.geolocation){$('executiveTaskMsg').textContent='Location is unavailable';return;}navigator.geolocation.getCurrentPosition(p=>{current.vehicle.latitude=p.coords.latitude;current.vehicle.longitude=p.coords.longitude;$('executiveTaskMsg').textContent='GPS recorded. Save the inspection to store it.';},e=>$('executiveTaskMsg').textContent=e.message,{enableHighAccuracy:true,timeout:15000});};
 $('cameraStart').onclick=async()=>{try{stopCamera();if(!navigator.mediaDevices?.getUserMedia)throw Error('Camera needs a supported browser and HTTPS');stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}},audio:false});$('inspectionCamera').srcObject=stream;$('inspectionCamera').hidden=false;$('cameraCapture').hidden=false;$('cameraStop').hidden=false;}catch(err){$('executiveTaskMsg').textContent='Camera: '+err.message;}};$('cameraStop').onclick=stopCamera;
 $('cameraCapture').onclick=async()=>{if(loadingPhoto)return;const video=$('inspectionCamera');if(!video.videoWidth){$('executiveTaskMsg').textContent='Wait for the camera preview';return;}loadingPhoto=true;$('cameraCapture').disabled=true;try{const canvas=document.createElement('canvas'),scale=Math.min(1,1600/video.videoWidth);canvas.width=Math.round(video.videoWidth*scale);canvas.height=Math.round(video.videoHeight*scale);canvas.getContext('2d').drawImage(video,0,0,canvas.width,canvas.height);const blob=await new Promise(r=>canvas.toBlob(r,'image/jpeg',0.85));if(!blob)throw Error('Could not capture photo');const fd=new FormData();fd.set('file',blob,'inspection.jpg');fd.set('kind','photo');fd.set('captureSource','in_app_camera');fd.set('capturedAt',new Date().toISOString());await data('/api/purchases/'+current.id+'/files',{method:'POST',body:fd});await task(current.id);$('executiveTaskMsg').textContent='Camera photo saved. Reopen the camera for another angle.';}catch(err){$('executiveTaskMsg').textContent=err.message;}finally{loadingPhoto=false;$('cameraCapture').disabled=false;}};
 $('executiveDocumentForm').onsubmit=async e=>{e.preventDefault();try{await data('/api/purchases/'+current.id+'/files',{method:'POST',body:new FormData(e.target)});await task(current.id);$('executiveTaskMsg').textContent='Document saved.';}catch(err){$('executiveTaskMsg').textContent=err.message;}};
 $('executiveFiles').onclick=async e=>{const b=e.target.closest('[data-document]');if(!b)return;const viewer=window.open('about:blank','_blank');if(viewer)viewer.opener=null;try{const r=await api('/api/purchases/'+current.id+'/files/'+b.dataset.document),url=URL.createObjectURL(await r.blob());if(viewer)viewer.location.href=url;else{const a=document.createElement('a');a.href=url;a.download='inspection-document';a.click();}setTimeout(()=>URL.revokeObjectURL(url),60000);}catch(err){viewer?.close();$('executiveTaskMsg').textContent=err.message;}};
 $('executiveSubmit').onclick=async()=>{try{await data('/api/purchases/'+current.id+'/submit',{method:'POST'});await task(current.id);$('executiveTaskMsg').textContent='Inspection completed. Your details, documents and photos have been submitted for admin review.';}catch(err){$('executiveTaskMsg').textContent=err.message;}};
 document.addEventListener('visibilitychange',()=>{if(document.hidden)stopCamera();});window.addEventListener('pagehide',stopCamera);(async()=>{try{if(await refresh())await signedIn((await data('/api/auth/me')).user);}catch{signedOut();}})();
})();
