(() => {
 const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const value=v=>v===null||v===undefined||v===''?'Not recorded':v;
 const money=v=>v===null||v===undefined||v===''?'Not recorded':new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR'}).format(Number(v));
 const parse=v=>{try{return typeof v==='string'?JSON.parse(v):v||{};}catch{return {};}};
 const fields=rows=>`<dl class="vehicle-data-grid">${rows.map(([label,v])=>`<div><dt>${esc(label)}</dt><dd>${esc(value(v))}</dd></div>`).join('')}</dl>`;
 const section=(title,rows)=>`<section class="vehicle-data-section"><h3>${esc(title)}</h3>${fields(rows)}</section>`;
 let generation=0;
 function render(b){
  const ticket=++generation,p=parse(b.detail_profile),s=parse(b.sale_profile),owner=window.bkAdminPermissions?.includes('owner');
  let frame=$('vehicleDataFrame');if(!frame){frame=document.createElement('section');frame.id='vehicleDataFrame';frame.className='vehicle-data-frame';$('editBikeForm').before(frame);}
  $('editBikeForm').hidden=true;
  const tabs=[['overview','Vehicle'],['photos','Photos'],['inspection','Inspection'],...(owner?[['accounts','Purchase & sale']]:[])];
  frame.innerHTML=`<div class="vehicle-frame-heading"><div><small>INVENTORY RECORD · BIKE #${esc(b.id)}</small><h2>${esc(b.registration_number||'Registration not recorded')}</h2><p>${esc(b.brand)} ${esc(b.model)} · ${esc(b.year)} · <strong>${esc(b.status)}</strong></p></div><button type="button" data-edit-vehicle>Edit bike details</button></div><div class="vehicle-frame-tabs" role="tablist" aria-label="Bike details">${tabs.map(([key,label],i)=>`<button type="button" id="vehicle-tab-${key}" role="tab" aria-controls="vehicle-pane-${key}" aria-selected="${i===0}" data-vehicle-tab="${key}">${label}</button>`).join('')}</div>
  <div id="vehicle-pane-overview" role="tabpanel" aria-labelledby="vehicle-tab-overview">${section('Vehicle identification',[['Bike ID',b.id],['Registration number',b.registration_number],['Make',b.brand],['Model',b.model],['Manufacturing year',b.year],['Engine number',p.engineNumber],['Chassis number',p.chassisNumber],['Registration date',p.registrationDate]])}${section('Vehicle information',[['Odometer (km)',b.kilometers_driven],['Number of owners',b.ownership_count],['Fuel type',b.fuel_type],['Description',b.condition_notes]])}</div>
  <div id="vehicle-pane-photos" role="tabpanel" aria-labelledby="vehicle-tab-photos" hidden><section class="vehicle-data-section"><h3>Vehicle gallery · ${b.images?.length||0} photos</h3><div class="vehicle-frame-gallery">${b.images?.map((img,i)=>`<a href="${esc(img.image_url)}" target="_blank" rel="noopener"><img src="${esc(img.image_url)}" alt="Bike ${esc(b.registration_number||b.id)} photo ${i+1}" loading="lazy"><span>Photo ${i+1} · Open full size</span></a>`).join('')||'<p>No bike photos uploaded.</p>'}</div></section></div>
  <div id="vehicle-pane-inspection" role="tabpanel" aria-labelledby="vehicle-tab-inspection" hidden>${section('Inspection checklist',[['Engine condition',p.engineCondition],['Engine noise',p.engineNoise],['Smoke',p.smoke],['Self start',p.selfStart],['Clutch plate',p.clutchPlate],['Timing chain noise',p.timingChainNoise],['Battery working',p.batteryWorking],['Chassis condition',p.chassis],['Body condition',p.bodyLine],['Keys',p.keysCount],['RC available',p.rcAvailable],['HP status',p.hpStatus],['NOC available',p.nocStatus],['Insurance',p.insuranceStatus],['Inspection notes',p.inspectionNotes]])}<div id="vehicle-inspection-source"></div></div>
  ${owner?`<div id="vehicle-pane-accounts" role="tabpanel" aria-labelledby="vehicle-tab-accounts" hidden>${section('Recorded purchase & expenses',[['Purchase price',money(s.purchasePrice)],['Transport',money(s.transportCost)],['Documents',money(s.documentCost)],['Other expenses',money(s.otherCost)]])}<div id="vehicle-purchase-source"></div>${section('Buyer & sale',[['Buyer',s.buyerName],['Business',s.buyerBusiness],['Mobile',s.buyerPhone],['Email',s.buyerEmail],['Sale price',money(s.salePrice)],['Received',money(s.paymentReceived)],['Balance',s.salePrice==null?null:money(Number(s.salePrice)-Number(s.paymentReceived||0))],['Sale date',s.saleDate],['Payment method',s.paymentMethod],['Payment reference',s.paymentReference],['Delivery date',s.deliveryDate],['Delivery released',s.deliveryReleased?'Yes':'No']])}</div>`:''}`;
  frame.onclick=e=>{const edit=e.target.closest('[data-edit-vehicle]');if(edit){const form=$('editBikeForm');form.hidden=!form.hidden;edit.textContent=form.hidden?'Edit bike details':'Hide edit form';if(!form.hidden)form.scrollIntoView({behavior:'smooth',block:'start'});return;}const tab=e.target.closest('[data-vehicle-tab]');if(!tab)return;frame.querySelectorAll('[role="tab"]').forEach(el=>el.setAttribute('aria-selected',String(el===tab)));frame.querySelectorAll('[role="tabpanel"]').forEach(el=>el.hidden=el.id!=='vehicle-pane-'+tab.dataset.vehicleTab);};
  frame.querySelector('[role="tablist"]').onkeydown=e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;const buttons=[...frame.querySelectorAll('[role="tab"]')],i=buttons.indexOf(document.activeElement);const next=e.key==='Home'?0:e.key==='End'?buttons.length-1:(i+(e.key==='ArrowRight'?1:-1)+buttons.length)%buttons.length;e.preventDefault();buttons[next].focus();buttons[next].click();};
  if(owner&&b.purchase_source?.id)loadSource(b.purchase_source.id,ticket,b.purchase_source.executive_name);
 }
 async function loadSource(id,ticket,executiveName){try{const response=await window.bkAdminApi('/api/purchases/'+encodeURIComponent(id));if(!response.ok)throw Error('Original inspection record is unavailable');const d=await response.json();if(ticket!==generation)return;const r=d.purchase,c=r.vehicle?.inspectionCharges||{};$('vehicle-inspection-source').innerHTML=section('Inspection record',[['Reference',r.reference||r.id],['Executive',executiveName],['Status',r.status],['Inspection time (UTC)',r.inspection_at],['Location',r.location],['Zone',r.vehicle?.inspectionZone],['Submitted (UTC)',r.submitted_at]]);$('vehicle-purchase-source').innerHTML=section('Purchase payment & refurb estimate',[['Seller',r.customer?.name],['Seller mobile',r.customer?.phone],['Purchase price',money(r.finances?.purchasePrice)],['Paid to seller',money(r.finances?.paymentPaid)],['Purchase balance',r.payment?.balance==null?null:money(r.payment.balance/100)],['Refurb estimate',c.totalPaise==null?null:money(c.totalPaise/100)]])+'<button type="button" data-source-record>Open complete purchase / inspection record</button>';$('vehicle-purchase-source').querySelector('button').onclick=()=>window.bkOpenPurchase?.(id);}catch(e){if(ticket===generation&&$('vehicle-inspection-source'))$('vehicle-inspection-source').textContent=e.message;}}
 window.addEventListener('bk-admin-bike',e=>render(e.detail));
 window.addEventListener('bk-admin-signed-out',()=>{generation++;$('vehicleDataFrame')?.remove();});
})();
