const express=require('express'),multer=require('multer'),fs=require('node:fs/promises'),path=require('node:path'),crypto=require('node:crypto');
const pool=require('../config/db');const {requireAuth}=require('../middleware/auth');const {findById}=require('../models/userModel');const {eligible,fail}=require('../utils/auctionRules');const {ensureBikeProfile}=require('../utils/bikeProfile');const bulk=require('../utils/bulkBikes');const {uploadRoot}=require('../middleware/upload');
const router=express.Router();const root=path.join(uploadRoot,'.bulk-import');
let ready;async function ensure(){if(!ready)ready=pool.query("CREATE TABLE IF NOT EXISTS bike_import_batches (id CHAR(36) PRIMARY KEY, owner_id VARCHAR(32) NOT NULL, payload LONGTEXT NOT NULL, result LONGTEXT NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4").catch(e=>{ready=null;throw e;});await ready;}
async function cleanExpired(){const [old]=await pool.query("SELECT id FROM bike_import_batches WHERE created_at < DATE_SUB(NOW(),INTERVAL 24 HOUR) AND (result IS NULL OR payload <> '[]') LIMIT 20");for(const row of old){if(!/^[0-9a-f-]{36}$/.test(row.id))continue;await fs.rm(path.join(root,row.id),{recursive:true,force:true});await pool.query("UPDATE bike_import_batches SET payload='[]' WHERE id=? AND result IS NOT NULL",[row.id]);await pool.query('DELETE FROM bike_import_batches WHERE id=? AND result IS NULL AND created_at < DATE_SUB(NOW(),INTERVAL 24 HOUR)',[row.id]);}}
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:25*1024*1024,files:2,fields:0,parts:2}}).fields([{name:'sheet',maxCount:1},{name:'photos',maxCount:1}]);
router.use(requireAuth,(req,res,next)=>findById(req.user.sub).then(user=>{eligible(user,['admin']);next();}).catch(next));
router.get('/template',async(req,res,next)=>{try{res.type('application/vnd.openxmlformats-officedocument.spreadsheetml.sheet').attachment('BikesKart_Bulk_Bikes.xlsx').send(Buffer.from(await bulk.template()));}catch(e){next(e);}});
async function duplicates(db,rows){const regs=rows.map(r=>r.body.registrationNumber).filter(r=>typeof r==='string'&&/^[A-Z0-9]{5,20}$/.test(r));if(!regs.length)return new Set();const [existing]=await db.query(`SELECT registration_number FROM bikes WHERE UPPER(REPLACE(REPLACE(registration_number,' ',''),'-','')) IN (${regs.map(()=>'?').join(',')})`,regs);return new Set(existing.map(r=>bulk.normalize(r.registration_number)));}
router.post('/preview',require('express-rate-limit')({windowMs:60000,limit:5,keyGenerator:req=>String(req.user.sub),message:{error:'Preview limit reached. Try again in a minute.'},standardHeaders:true,legacyHeaders:false}),upload,async(req,res,next)=>{
 let dir;try{
  await ensure();await cleanExpired();let rows,errors;try{rows=await bulk.readSheet(req.files?.sheet?.[0]);errors=await bulk.matchPhotos(req.files?.photos?.[0],rows);}catch(e){if(!e.status){e.status=400;e.expose=true;}throw e;}const existing=await duplicates(pool,rows);for(const row of rows)if(existing.has(row.body.registrationNumber))row.errors.push('Registration already exists in Bike Inventory');
  const canImport=!errors.length&&rows.every(r=>!r.errors.length);let previewId=null;
  if(canImport){previewId=crypto.randomUUID();dir=path.join(root,previewId);await fs.mkdir(dir,{recursive:true,mode:0o700});for(const row of rows){const staged=[];for(const photo of row.photos){const filename=crypto.randomUUID()+photo.ext;await fs.writeFile(path.join(dir,filename),photo.buffer,{flag:'wx',mode:0o600});staged.push(filename);}row.photos=staged;}await pool.query('INSERT INTO bike_import_batches (id,owner_id,payload) VALUES (?,?,?)',[previewId,String(req.user.sub),JSON.stringify(rows)]);}
  res.json({previewId,canImport,errors,rows:rows.map(r=>({row:r.row,registrationNumber:r.body.registrationNumber,brand:r.body.brand,model:r.body.model,year:r.body.year,photoCount:r.photos.length,errors:r.errors,details:r.body}))});
 }catch(e){if(dir)await fs.rm(dir,{recursive:true,force:true}).catch(()=>{});next(e);}
});
router.post('/:id/confirm',async(req,res,next)=>{
 let connection,locked=false,committed=false,commitStarted=false;const copied=[];try{
  if(!/^[0-9a-f-]{36}$/.test(req.params.id))fail('Invalid preview ID');await ensure();await ensureBikeProfile(pool);connection=await pool.getConnection();
  const [[lock]]=await connection.query("SELECT GET_LOCK(CONCAT(DATABASE(),':bulk_bikes'),10) AS acquired");if(Number(lock.acquired)!==1)fail('Another bike import is running. Try again.',409);locked=true;await connection.beginTransaction();
  const [[batch]]=await connection.query('SELECT *,created_at < DATE_SUB(NOW(),INTERVAL 24 HOUR) AS expired FROM bike_import_batches WHERE id=? AND owner_id=? FOR UPDATE',[req.params.id,String(req.user.sub)]);if(!batch)fail('Preview not found',404);if(batch.result){await connection.commit();committed=true;return res.json(JSON.parse(batch.result));}if(batch.expired)fail('Preview expired. Upload the files again',410);
  const rows=JSON.parse(batch.payload);if((await duplicates(connection,rows)).size)fail('A registration was added since preview. Upload again to review duplicates.',409);
  const ids=[];await fs.mkdir(path.join(uploadRoot,'bikes'),{recursive:true});
  for(const row of rows){const b=row.body;const [insert]=await connection.query("INSERT INTO bikes (dealer_id,brand,model,year,registration_number,kilometers_driven,ownership_count,fuel_type,condition_notes,detail_profile,status) VALUES (?,?,?,?,?,?,?,?,?,?,'draft')",[req.user.sub,b.brand,b.model,Number(b.year),b.registrationNumber,b.kilometersDriven===''||b.kilometersDriven==null?null:Number(b.kilometersDriven),b.ownershipCount===''||b.ownershipCount==null?null:Number(b.ownershipCount),b.fuelType||null,b.conditionNotes||null,JSON.stringify(b.detailProfile)]);ids.push(insert.insertId);
   for(const [index,filename] of row.photos.entries()){if(!/^[0-9a-f-]{36}\.(jpg|png|webp)$/.test(filename))fail('Invalid staged photo');const publicName=crypto.randomUUID()+path.extname(filename),destination=path.join(uploadRoot,'bikes',publicName);await fs.copyFile(path.join(root,batch.id,filename),destination,require('node:fs').constants.COPYFILE_EXCL);copied.push(destination);await connection.query('INSERT INTO bike_images (bike_id,image_url,sort_order) VALUES (?,?,?)',[insert.insertId,'/uploads/bikes/'+publicName,index]);}
  }
  const result={imported:ids.length,bikeIds:ids};await connection.query('UPDATE bike_import_batches SET result=? WHERE id=?',[JSON.stringify(result),batch.id]);commitStarted=true;await connection.commit();committed=true;await fs.rm(path.join(root,batch.id),{recursive:true,force:true}).catch(()=>{});res.json(result);
 }catch(e){if(connection&&!committed)await connection.rollback().catch(()=>{});if(!committed&&!commitStarted)await Promise.all(copied.map(file=>fs.unlink(file).catch(()=>{})));next(e);}finally{if(locked)await connection.query("SELECT RELEASE_LOCK(CONCAT(DATABASE(),':bulk_bikes'))").catch(()=>{});connection?.release();}
});
module.exports=router;
