const router=require('express').Router(),pool=require('../config/db'),ops=require('../utils/adminOperations'),p=require('../utils/purchases'),roles=require('../utils/staffRoles'),crypto=require('node:crypto');router.use(require('../middleware/auth').requireAuth,require('../middleware/adminPermissions').requireAdminScope());const route=fn=>(req,res,next)=>Promise.resolve(fn(req,res)).catch(next);
router.use('/:role',async(req,res,next)=>{try{roles.allow(req.adminPermissions,req.params.role);await p.ensurePurchases(pool);next();}catch(e){next(e);}});
async function tx(fn){const c=await pool.getConnection();try{await c.beginTransaction();const r=await fn(c);await c.commit();return r;}catch(e){await c.rollback();throw e;}finally{c.release();}}function id(req){if(!/^[0-9a-f-]{36}$/.test(req.params.id))ops.error('Invalid record ID');return req.params.id;}
router.get('/:role',route(async(req,res)=>{roles.allow(req.adminPermissions,req.params.role);const page=Math.max(1,parseInt(req.query.page)||1),search='%'+String(req.query.search||'').slice(0,100)+'%';const [rows]=await pool.query("SELECT id,bike_id,status,assigned_to,inspection_at,location,version,customer,vehicle FROM bike_purchases WHERE JSON_UNQUOTE(JSON_EXTRACT(vehicle,'$.registrationNumber')) LIKE ? ORDER BY created_at DESC LIMIT 30 OFFSET ?",[search,(page-1)*30]);res.json({rows:rows.map(r=>roles.sanitize(r,req.params.role)),page});}));
router.get('/purchase/executives',route(async(req,res)=>{roles.allow(req.adminPermissions,'purchase');const [rows]=await pool.query("SELECT id,full_name FROM users WHERE role='executive' AND is_active=1 AND is_verified=1 ORDER BY full_name");res.json({rows});}));
router.post('/purchase',route(async(req,res)=>{roles.allow(req.adminPermissions,'purchase');if(Object.keys(req.body).some(k=>!['registrationNumber','phone','zone','executiveId'].includes(k)))ops.error('Unknown assignment field');const c=p.customer({phone:req.body.phone}),v=p.vehicle({registrationNumber:req.body.registrationNumber});if(!c.phone||!v.registrationNumber)ops.error('Registration and mobile required');v.inspectionZone=p.zone(req.body.zone);const recordId=crypto.randomUUID();await tx(async db=>{const [[u]]=await db.query("SELECT id FROM users WHERE id=? AND role='executive' AND is_active=1 AND is_verified=1",[req.body.executiveId]);if(!u)ops.error('Choose an active executive');await db.query("INSERT INTO bike_purchases (id,customer,vehicle,finances,assigned_to,status,created_by) VALUES (?,?,?,?,?,'assigned',?)",[recordId,JSON.stringify(c),JSON.stringify(v),'{}',u.id,String(req.user.sub)]);await ops.audit(db,req.user.sub,'purchase-admin.assign',recordId,{executiveId:u.id,registration:v.registrationNumber});});res.status(201).json({id:recordId});}));
router.patch('/:role/:id',route(async(req,res)=>{const role=req.params.role;roles.allow(req.adminPermissions,role);await tx(async db=>{const [[r]]=await db.query('SELECT * FROM bike_purchases WHERE id=? FOR UPDATE',[id(req)]);if(!r)ops.error('Record not found',404);if(Number(req.body.version)!==r.version)ops.error('Record changed. Reload first',409);const v=p.json(r.vehicle);if(role==='purchase'){if(Object.keys(req.body).some(k=>!['version','proposedPrice','notes'].includes(k)))ops.error('Purchase admins cannot alter payment accounts',403);const price=ops.cents(req.body.proposedPrice);if(price===null)ops.error('Enter proposed customer price');v.purchaseProposal={amount:(price/100).toFixed(2),notes:p.text(req.body.notes,2000,'proposal notes'),proposedBy:String(req.user.sub),proposedAt:new Date().toISOString()};}else if(role==='mechanic'){if(Object.keys(req.body).some(k=>!['version','inspectionCharges','notes'].includes(k)))ops.error('Only repair estimates and mechanic notes are allowed',403);v.inspectionCharges=p.requireCharges(req.body.inspectionCharges);v.mechanicReview={notes:p.text(req.body.notes,3000,'mechanic notes'),reviewedBy:String(req.user.sub),reviewedAt:new Date().toISOString()};}else ops.error('Use the document review action',403);await db.query('UPDATE bike_purchases SET vehicle=?,version=version+1 WHERE id=?',[JSON.stringify(v),r.id]);await ops.audit(db,req.user.sub,'specialist.'+role,r.id,{proposal:v.purchaseProposal,mechanicReview:v.mechanicReview});});res.json({saved:true});}));
const fs=require('node:fs/promises'),path=require('node:path'),root=path.join(require('../middleware/upload').uploadRoot,'inspections'),kinds=['rc','noc','kyc','insurance','puc','challan','vahan','undertaking','form29','form30','form35'];
async function documentRecord(req){roles.allow(req.adminPermissions,'documents');const [[r]]=await pool.query('SELECT id FROM bike_purchases WHERE id=?',[id(req)]);if(!r)ops.error('Record not found',404);await pool.query("CREATE TABLE IF NOT EXISTS purchase_document_reviews (document_id CHAR(36) PRIMARY KEY,status VARCHAR(30) NOT NULL,reviewed_by VARCHAR(32) NOT NULL,notes VARCHAR(2000) NULL,reviewed_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB");}
router.get('/documents/:id/files',route(async(req,res)=>{await documentRecord(req);const [rows]=await pool.query("SELECT d.id,d.kind,d.filename,d.created_at,r.status,r.notes,r.reviewed_by,r.reviewed_at FROM purchase_documents d LEFT JOIN purchase_document_reviews r ON r.document_id=d.id WHERE d.purchase_id=? AND d.kind IN (?) ORDER BY d.created_at DESC",[id(req),kinds]);res.json({rows,kinds});}));
const ext={'image/jpeg':'.jpg','image/png':'.png','image/webp':'.webp','application/pdf':'.pdf'},upload=require('multer')({storage:require('multer').diskStorage({destination:async(req,f,cb)=>{try{await fs.mkdir(root,{recursive:true,mode:0o700});cb(null,root);}catch(e){cb(e);}},filename:(req,f,cb)=>cb(null,crypto.randomUUID()+ext[f.mimetype])}),limits:{fileSize:8*1024*1024,files:1},fileFilter:(req,f,cb)=>{if(!ext[f.mimetype]){const e=Error('Use JPG, PNG, WEBP or PDF');e.status=400;return cb(e);}cb(null,true);}}).single('file');
router.post('/documents/:id/files',async(req,res,next)=>{try{await documentRecord(req);next();}catch(e){next(e);}},upload,route(async(req,res)=>{let saved=false;try{if(!req.file||!kinds.includes(req.body.kind))ops.error('Choose a valid document type and file');await tx(async db=>{const docId=crypto.randomUUID();await db.query('INSERT INTO purchase_documents (id,purchase_id,kind,filename,uploaded_by) VALUES (?,?,?,?,?)',[docId,id(req),req.body.kind,req.file.filename,String(req.user.sub)]);await ops.audit(db,req.user.sub,'documents.upload',id(req),{documentId:docId,kind:req.body.kind});});saved=true;res.status(201).json({saved:true});}finally{if(!saved&&req.file)await fs.unlink(req.file.path).catch(()=>{});}}));
router.patch('/documents/:id/files/:docId',route(async(req,res)=>{await documentRecord(req);if(!['Verified','Needs correction'].includes(req.body.status))ops.error('Invalid review status');await tx(async db=>{const [[doc]]=await db.query('SELECT kind FROM purchase_documents WHERE id=? AND purchase_id=? FOR UPDATE',[req.params.docId,id(req)]);if(!doc||!kinds.includes(doc.kind))ops.error('Document not found',404);await db.query('INSERT INTO purchase_document_reviews (document_id,status,reviewed_by,notes) VALUES (?,?,?,?) ON DUPLICATE KEY UPDATE status=VALUES(status),reviewed_by=VALUES(reviewed_by),notes=VALUES(notes),reviewed_at=UTC_TIMESTAMP()',[req.params.docId,req.body.status,String(req.user.sub),p.text(req.body.notes,2000,'review notes')]);await ops.audit(db,req.user.sub,'documents.review',id(req),{documentId:req.params.docId,status:req.body.status});});res.json({saved:true});}));
router.get('/documents/:id/files/:docId',route(async(req,res)=>{await documentRecord(req);const [[doc]]=await pool.query('SELECT kind,filename FROM purchase_documents WHERE id=? AND purchase_id=?',[req.params.docId,id(req)]);if(!doc||!kinds.includes(doc.kind)||! /^[a-f0-9-]{36}\.(jpg|png|webp|pdf)$/.test(doc.filename))ops.error('Document not found',404);res.set('Cache-Control','no-store');res.sendFile(path.join(root,doc.filename));}));
module.exports=router;
