const {requireAdminScope}=require("../middleware/adminPermissions");
const express=require('express'),crypto=require('node:crypto');const pool=require('../config/db');const {requireAuth}=require('../middleware/auth');const {findById}=require('../models/userModel');const {eligible,positiveId,fail}=require('../utils/auctionRules');const {ensureDealerProfile}=require('../utils/dealerProfile');const messages=require('../utils/winnerMessages');
const router=express.Router();
const select="SELECT a.id,a.bike_id,a.winner_id,a.highest_bid,a.closed_at,b.brand,b.model,b.registration_number,u.full_name,u.email,u.phone,u.business_name FROM auctions a JOIN bikes b ON b.id=a.bike_id JOIN users u ON u.id=a.winner_id WHERE a.status='closed' AND a.result='sold'";
let ready;async function ensure(){await ensureDealerProfile(pool);if(!ready)ready=pool.query("CREATE TABLE IF NOT EXISTS auction_winner_contacts (id CHAR(36) PRIMARY KEY, auction_id BIGINT UNSIGNED NOT NULL, admin_id VARCHAR(32) NOT NULL, channel VARCHAR(16) NOT NULL, recipient VARCHAR(190) NOT NULL, message TEXT NOT NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, marked_sent_at DATETIME NULL, marked_sent_by VARCHAR(32) NULL, KEY idx_winner_contacts (auction_id,created_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4").catch(e=>{ready=null;throw e;});await ready;}
router.use(requireAuth,(req,res,next)=>findById(req.user.sub).then(u=>{eligible(u,['admin']);next();}).catch(next));
router.use(requireAdminScope("notifications"));
router.get('/',async(req,res,next)=>{try{await ensure();const page=Math.min(Math.max(parseInt(req.query.page,10)||1,1),10000);const [rows]=await pool.query(select+' ORDER BY a.closed_at DESC,a.id DESC LIMIT 20 OFFSET ?',[(page-1)*20]);const [[{total}]]=await pool.query("SELECT COUNT(*) AS total FROM auctions WHERE status='closed' AND result='sold' AND winner_id IS NOT NULL");let contacts=[];if(rows.length){[contacts]=await pool.query(`SELECT id,auction_id,channel,recipient,created_at,marked_sent_at FROM auction_winner_contacts WHERE auction_id IN (${rows.map(()=>'?').join(',')}) ORDER BY created_at DESC,id DESC LIMIT 500`,rows.map(r=>r.id));}res.json({rows:rows.map(row=>({...row,whatsappAvailable:Boolean(messages.whatsAppPhone(row.phone)),contacts:contacts.filter(c=>String(c.auction_id)===String(row.id))})),total,page,defaultInstructions:messages.defaultInstructions});}catch(e){next(e);}});
router.post('/:id/draft',async(req,res,next)=>{try{await ensure();const id=positiveId(req.params.id);const [[winner]]=await pool.query(select+' AND a.id=?',[id]);if(!winner)fail('Winning auction not found',404);const draft=messages.message(winner,req.body.instructions);const destination=messages.link(req.body.channel,winner,draft);const contactId=crypto.randomUUID();await pool.query('INSERT INTO auction_winner_contacts (id,auction_id,admin_id,channel,recipient,message) VALUES (?,?,?,?,?,?)',[contactId,id,String(req.user.sub),req.body.channel,destination.recipient,draft.text]);await require('../utils/adminOperations').audit(pool,req.user.sub,'notification.draft',id,{channel:req.body.channel,contactId});res.json({contactId,...draft,...destination,channel:req.body.channel,status:'draft_prepared'});}catch(e){next(e);}});
router.post('/contacts/:id/mark-sent',async(req,res,next)=>{try{await ensure();if(!/^[0-9a-f-]{36}$/.test(req.params.id))fail('Invalid notification record');const [r]=await pool.query('UPDATE auction_winner_contacts SET marked_sent_at=COALESCE(marked_sent_at,NOW()),marked_sent_by=COALESCE(marked_sent_by,?) WHERE id=?',[String(req.user.sub),req.params.id]);if(!r.affectedRows){const [[record]]=await pool.query('SELECT id FROM auction_winner_contacts WHERE id=?',[req.params.id]);if(!record)fail('Notification record not found',404);}await require('../utils/adminOperations').audit(pool,req.user.sub,'notification.mark-sent',req.params.id,{});res.json({marked:true,status:'admin_marked_sent'});}catch(e){next(e);}});
module.exports=router;
