const {test,before,after}=require('node:test'),assert=require('node:assert/strict');Object.assign(process.env,{DB_HOST:'unused',DB_USER:'unused',DB_PASSWORD:'unused',DB_NAME:'unused',JWT_SECRET:'admin-ops-secret',NODE_ENV:'test'});
let timerAuction={id:7,status:'open',ends_at:'2026-10-07T10:30:00.000Z'},timerNow=Date.parse('2026-10-07T10:00:00Z'),timerUpdates=0;
let oldAuction={id:7,bike_id:1,status:'closed',result:'unsold',bike_status:'ready'},blockedAuction=false;
let userId=1,scopes=null,active=1,role='admin',sale={salePrice:'100',paymentReceived:'100',documents:[{kind:'deliveryPhoto',filename:'123-0123456789abcdef.jpg'},{kind:'saleReceipt',filename:'124-0123456789abcdef.pdf'}]},saved=0,audits=0,commits=0,rollbacks=0,snapshot;
const pool={query:async(sql,p=[])=>{if(sql.startsWith('SELECT bike_id FROM auctions'))return [[{bike_id:1}]];if(sql.startsWith('SELECT id,customer,vehicle,finances'))return [[{id:'purchase1',customer:'{"phone":"9900000000"}',vehicle:'{}',finances:'{"purchasePrice":"50000"}'}]];if(sql.startsWith('SELECT id,status,DATE_FORMAT'))return [[timerAuction]];if(sql.startsWith('SELECT UNIX_TIMESTAMP'))return [[{now_ms:timerNow}]];if(sql.startsWith('UPDATE auctions SET ends_at')){timerAuction.ends_at=p[0].replace(' ','T')+'Z';timerUpdates++;return [{}];}if(sql.startsWith('SELECT a.*,b.status AS bike_status'))return [[oldAuction]];if(sql.startsWith("SELECT id FROM auctions WHERE bike_id"))return [blockedAuction?[{id:9}]:[]];if(sql.startsWith('SELECT CAST(id AS CHAR) AS setting_value FROM users'))return [[{setting_value:'1'}]];if(sql.startsWith('INSERT INTO admin_settings'))return [{}];if(sql.startsWith('SHOW COLUMNS'))return [[{Field:'reference_number'},{Field:'admin_scopes'},{Field:'sale_profile'},{Field:'phone'},{Field:'business_name'},{Field:'gst_number'}]];if(sql.startsWith('CREATE TABLE'))return [[]];if(sql.startsWith('SELECT id,role,is_active'))return [[{id:userId,role,is_active:active,admin_scopes:scopes}]];if(sql.startsWith('SELECT id,sale_profile'))return [[{id:1,sale_profile:JSON.stringify(sale)}]];if(sql.startsWith('SELECT highest_bid'))return [[{highest_bid:'100'}]];if(sql.startsWith('UPDATE bikes SET sale_profile')){sale=JSON.parse(p[0]);saved++;return [{}];}if(sql.startsWith('INSERT INTO admin_activity')){audits++;return [{}];}if(sql.startsWith('SELECT b.id'))return [[{id:1,brand:'Honda',model:'Activa',status:'sold',sale_profile:JSON.stringify(sale),highest_bid:'100',winner_name:'Dealer',closed_at:'2026-10-07'}]];throw Error(sql);},getConnection:async()=>({query:(...a)=>pool.query(...a),beginTransaction:async()=>{snapshot=JSON.parse(JSON.stringify(sale));},commit:async()=>{commits++;},rollback:async()=>{sale=snapshot;rollbacks++;},release(){}})};
const dbPath=require.resolve('../src/config/db');require.cache[dbPath]={id:dbPath,filename:dbPath,loaded:true,exports:pool};const auctionPath=require.resolve('../src/models/auctionModel');require.cache[auctionPath]={id:auctionPath,filename:auctionPath,loaded:true,exports:{closeDue:async()=>{}}};const bikePath=require.resolve('../src/models/bikeModel');require.cache[bikePath]={id:bikePath,filename:bikePath,loaded:true,exports:{getBikeById:async()=>({id:1,brand:'Honda',model:'Activa',sale_profile:{purchasePrice:'50000'},detail_profile:{engineNumber:'ENG1'},images:[],dealer_id:1,rc_document_url:'/private'})}};const tokens=require('../src/utils/tokens');let server,base;const headers=()=>({Authorization:'Bearer '+tokens.signAccessToken({id:userId,role:'admin'}),'Content-Type':'application/json'});
before(async()=>{const app=require('express')();app.use(require('express').json());app.use('/ops',require('../src/routes/operationRoutes'));app.use((e,req,res,next)=>res.status(e.status||500).json({error:e.message}));server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));base='http://127.0.0.1:'+server.address().port;});after(()=>new Promise(r=>server.close(r)));
const patch=body=>fetch(base+'/ops/bikes/1',{method:'PATCH',headers:headers(),body:JSON.stringify(body)});
test('staff scope and current account status are enforced even with owner JWT',async()=>{userId=2;scopes='["inventory"]';let r=await patch({paymentConfirmed:true});assert.equal(r.status,403);assert.equal(saved,0);active=0;r=await patch({rcProgress:'Received'});assert.equal(r.status,403);active=1;role='dealer';r=await patch({rcProgress:'Received'});assert.equal(r.status,403);role='admin';scopes=null;userId=1;});
test('handover failures roll back; confirmed payment and evidence release atomically with audit',async()=>{let r=await patch({deliveryReleased:true,receiptSigned:true});assert.equal(r.status,409);assert.equal(rollbacks,1);assert.equal(audits,0);r=await patch({paymentConfirmed:true,collectedBy:'Buyer',deliveryDate:'2026-10-07',deliveryReleased:true,receiptSigned:true});assert.equal(r.status,200);assert.equal(sale.deliveryReleased,true);assert.equal(audits,1);assert.equal(commits,1);r=await patch({paymentReceived:'20'});assert.equal(r.status,409);assert.equal(sale.paymentReceived,'100');});
test('old accounts permissions cannot bypass main-admin-only payments or handover',async()=>{userId=2;scopes='["accounts"]';let r=await patch({collectedBy:'Someone else'});assert.equal(r.status,403);r=await patch({paymentDeadline:'2026-10-10'});assert.equal(r.status,403);assert.equal(sale.paymentDeadline,undefined);assert.equal((await fetch(base+'/ops/activity',{headers:headers()})).status,403);scopes=null;userId=1;});
test('unknown fields are rejected rather than persisted',async()=>{assert.equal((await patch({adminScopes:['owner']})).status,400);});
test('reports produce accurate totals and a downloadable Excel workbook',async()=>{const d=await (await fetch(base+'/ops/reports',{headers:headers()})).json();assert.equal(d.summary.sold,1);assert.equal(d.summary.outstandingCents,0);assert.equal(d.summary.pendingDeliveries,0);const r=await fetch(base+'/ops/reports?export=xlsx',{headers:headers()});assert.equal(r.status,200);const book=new (require('exceljs').Workbook)();await book.xlsx.load(Buffer.from(await r.arrayBuffer()));assert.equal(book.getWorksheet('Bike records').getRow(2).getCell(5).value,'Dealer');});

test('re-auction preparation keeps completed data and rejects winning or active vehicles',async()=>{const get=()=>fetch(base+'/ops/auctions/7/reauction',{headers:headers()});assert.equal((await get()).status,200);assert.equal(oldAuction.result,'unsold');oldAuction.result='sold';assert.equal((await get()).status,409);oldAuction.result='unsold';blockedAuction=true;assert.equal((await get()).status,409);blockedAuction=false;oldAuction.status='cancelled';assert.equal((await get()).status,200);oldAuction.bike_status='sold';assert.equal((await get()).status,409);oldAuction.bike_status='ready';userId=2;scopes='["documents"]';assert.equal((await get()).status,403);scopes=null;userId=1;});

test('timer extensions add to the existing end time and reject expired, closed or unauthorized changes',async()=>{const extend=minutes=>fetch(base+'/ops/auctions/7/extend',{method:'POST',headers:headers(),body:JSON.stringify({minutes})});let r=await extend(10);assert.equal(r.status,200);assert.equal((await r.json()).endsAt,'2026-10-07T10:40:00.000Z');assert.equal(timerUpdates,1);for(const value of [0,-1,1441,1.5,'10'])assert.equal((await extend(value)).status,400);timerNow=Date.parse(timerAuction.ends_at);assert.equal((await extend(5)).status,409);timerNow-=60000;timerAuction.status='closed';assert.equal((await extend(5)).status,409);timerAuction.status='open';userId=2;scopes='["documents"]';assert.equal((await extend(5)).status,403);assert.equal(timerUpdates,1);scopes=null;userId=1;});

test('auction vehicle details include main-admin purchase records and hide finances from auction staff',async()=>{const get=()=>fetch(base+'/ops/auctions/7/vehicle',{headers:headers()});let r=await get();assert.equal(r.status,200);let d=await r.json();assert.equal(d.bike.sale_profile.purchasePrice,'50000');assert.equal(d.purchase.finances.purchasePrice,'50000');userId=2;scopes='["auctions"]';r=await get();assert.equal(r.status,200);d=await r.json();assert.equal(d.bike.sale_profile,undefined);assert.equal(d.purchase,null);assert.equal(d.bike.rc_document_url,undefined);assert.equal(d.bike.detail_profile.engineNumber,'ENG1');scopes='["documents"]';assert.equal((await get()).status,403);scopes=null;userId=1;});

test('only main admin can release a winning bid for re-auction',async()=>{userId=2;scopes='["auctions"]';const r=await fetch(base+'/ops/auctions/7/release-award',{method:'POST',headers:headers(),body:JSON.stringify({reason:'Dealer declined'})});assert.equal(r.status,403);scopes=null;userId=1;});

test('auction staff cannot mark the winning bid sold without main-admin approval',async()=>{userId=2;scopes='["auctions"]';const r=await fetch(base+'/ops/auctions/7/confirm',{method:'POST',headers:headers()});assert.equal(r.status,403);scopes=null;userId=1;});
