const {test,before,after}=require('node:test');
const assert=require('node:assert/strict');
Object.assign(process.env,{DB_HOST:'unused',DB_USER:'unused',DB_PASSWORD:'unused',DB_NAME:'unused',JWT_SECRET:'test-only-secret',NODE_ENV:'test'});
const mock=(file,exports)=>{const path=require.resolve(file);require.cache[path]={id:path,filename:path,loaded:true,exports};};
mock('../src/config/db',{query:async sql=>sql.startsWith('SELECT CAST(id AS CHAR) AS setting_value FROM users')?[[{setting_value:'3'}]]:sql.startsWith('SELECT id,role,is_active')?[[{...account,admin_scopes:null}]]:sql.startsWith('SHOW COLUMNS')?[[{Field:'admin_scopes'}]]:[[]]});
let account={id:3,role:'dealer',is_active:1,is_verified:1},writes=0,view;
mock('../src/models/userModel',{findById:async()=>account});
mock('../src/models/auctionModel',{list:async(user)=>{view=user;return {rows:[]};},detail:async()=>({auction:{id:1}}),create:async()=>{writes++;return {id:1};},bid:async()=>{writes++;return {amount:50000};},cancel:async()=>{writes++;return {cancelled:true};}});
const express=require('express'),app=express();app.use(express.json());app.use('/api/auctions',require('../src/routes/auctionRoutes'));app.use((err,req,res,next)=>res.status(err.status||500).json({error:err.message}));
const {signAccessToken}=require('../src/utils/tokens');
let server,base;
before(async()=>{server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));base=`http://127.0.0.1:${server.address().port}/api/auctions`;});
after(()=>new Promise(r=>server.close(r)));
const headers=()=>({Authorization:`Bearer ${signAccessToken({id:3,role:'dealer'})}`,'Content-Type':'application/json'});
test('auction endpoints require authentication',async()=>{assert.equal((await fetch(base)).status,401);});
test('dealer cannot create or cancel auctions',async()=>{writes=0;assert.equal((await fetch(base,{method:'POST',headers:headers(),body:'{}'})).status,403);assert.equal((await fetch(base+'/1/cancel',{method:'POST',headers:headers()})).status,403);assert.equal(writes,0);});
test('disabled and unverified accounts lose viewing access immediately',async()=>{for(const field of ['is_active','is_verified']){account[field]=0;assert.equal((await fetch(base,{headers:headers()})).status,403);account[field]=1;}});
test('viewer identity comes from current account data',async()=>{assert.equal((await fetch(base,{headers:headers()})).status,200);assert.equal(view.id,3);assert.equal(view.role,'dealer');});
test('invalid auction IDs are rejected',async()=>{for(const id of ['0','-1','1.2','abc'])assert.equal((await fetch(base+'/'+id,{headers:headers()})).status,400);});
test('live admin role permits creation even with an older role in JWT',async()=>{account.role='admin';assert.equal((await fetch(base,{method:'POST',headers:headers(),body:'{"bikeId":1}'})).status,201);account.role='dealer';});
