const {test}=require('node:test'),assert=require('node:assert/strict');const Excel=require('exceljs'),archiver=require('archiver');const bulk=require('../src/utils/bulkBikes');
async function zip(entries){return new Promise((resolve,reject)=>{const z=archiver('zip'),chunks=[];z.on('data',c=>chunks.push(c));z.on('end',()=>resolve(Buffer.concat(chunks)));z.on('error',reject);for(const [name,buffer] of Object.entries(entries))z.append(buffer,{name});z.finalize();});}
const sheet=csv=>({originalname:'bikes.csv',buffer:Buffer.from(csv)});
test('Excel template round trip imports plain values and preserves zero keys',async()=>{const wb=new Excel.Workbook();await wb.xlsx.load(await bulk.template());const s=wb.getWorksheet('Bikes');s.columns=bulk.columns.map(key=>({key}));s.addRow({brand:'Honda',model:'Activa',year:2024,registrationNumber:'ka01 ab1234',keysCount:0,engineCondition:'Good',vehicleRating:4});const rows=await bulk.readSheet({originalname:'bikes.xlsx',buffer:await wb.xlsx.writeBuffer()});assert.deepEqual(rows[0].errors,[]);assert.equal(rows[0].body.registrationNumber,'KA01AB1234');assert.equal(rows[0].body.detailProfile.keysCount,0);});
test('CSV supports quoted description, catches duplicates and invalid inspections',async()=>{const rows=await bulk.readSheet(sheet('brand,model,year,registrationNumber,conditionNotes,vehicleRating\nHonda,Activa,2024,KA01AB1234,"Clean, serviced",4\nHonda,Activa,2024,KA01AB1234,Notes,9\nHonda,Activa,2024,KA02AB1234,Notes,9'));assert.equal(rows[0].body.conditionNotes,'Clean, serviced');assert.ok(rows[1].errors.some(e=>e.includes('Duplicate')));assert.ok(rows[2].errors.some(e=>e.includes('vehicleRating')));});
test('formulas, changed headers and over 100 bikes are rejected',async()=>{const wb=new Excel.Workbook();await wb.xlsx.load(await bulk.template());wb.getWorksheet('Bikes').columns=bulk.columns.map(key=>({key}));wb.getWorksheet('Bikes').addRow({brand:'Honda',model:{formula:'1+1'},year:2024,registrationNumber:'KA01AB1234'});const rows=await bulk.readSheet({originalname:'bikes.xlsx',buffer:await wb.xlsx.writeBuffer()});assert.ok(rows[0].errors.length);await assert.rejects(bulk.readSheet(sheet('brand,model,wrong\nx,y,z')));await assert.rejects(bulk.readSheet(sheet('brand,model,year,registrationNumber\n'+Array.from({length:101},(_,i)=>`Honda,Activa,2024,KA01AB${1000+i}`).join('\n'))));});
test('ZIP photos match registration folders and reject unmatched or fake photos',async()=>{const rows=await bulk.readSheet(sheet('brand,model,year,registrationNumber\nHonda,Activa,2024,KA01AB1234'));const jpeg=Buffer.from([255,216,255,217]);const errors=await bulk.matchPhotos({originalname:'photos.zip',buffer:await zip({'KA01AB1234/front.jpg':jpeg,'KA01AB1234/fake.jpg':Buffer.from('<html>'),'KA99AB1234/front.jpg':jpeg})},rows);assert.equal(rows[0].photos.length,1);assert.ok(rows[0].errors.some(e=>e.includes('real JPG')));assert.ok(errors.some(e=>e.includes('No bike row')));});
test('ZIP expansion is bounded before extracting and malformed archives fail',async()=>{const buffer=await zip({'KA01AB1234/a.jpg':Buffer.alloc(1024)});await assert.rejects(bulk.zipEntries(buffer,{maxBytes:100,maxFile:100}));await assert.rejects(bulk.zipEntries(Buffer.from('not a zip')));});
module.exports={zip};
