const {test,before,after}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),os=require('node:os'),path=require('node:path');
Object.assign(process.env,{DB_HOST:'unused',DB_USER:'unused',DB_PASSWORD:'unused',DB_NAME:'unused',JWT_SECRET:'bulk-test-secret',NODE_ENV:'test'});
const batches=new Map();let bikes=[],images=[],nextId=1,failImages=false,loseCommit=false,root,server,base,snapshot;
const pool={async query(sql,p=[]){
 if(sql.startsWith('SELECT id,role,is_active,is_verified,admin_scopes'))return [[{id:p[0],role:Number(p[0])===9?'dealer':'admin',is_active:1,is_verified:1,admin_scopes:null}]];
 if(sql.startsWith('INSERT INTO admin_activity'))return [{}];
 if(sql.startsWith('CREATE TABLE')||sql.startsWith('ALTER TABLE'))return [[]];if(sql.startsWith('SHOW COLUMNS'))return [[{Field:'detail_profile'}]];
 if(sql.startsWith('SELECT id FROM bike_import'))return [[]];
 if(sql.startsWith('SELECT registration_number'))return [bikes.filter(b=>p.includes(b.registration_number))];
 if(sql.startsWith('INSERT INTO bike_import_batches')){batches.set(p[0],{id:p[0],owner_id:p[1],payload:p[2],result:null,expired:0});return [{}];}
 if(sql.includes('GET_LOCK'))return [[{acquired:1}]];if(sql.includes('RELEASE_LOCK'))return [[{}]];
 if(sql.startsWith('SELECT *,created_at')){const b=batches.get(p[0]);return [[...(b&&b.owner_id===p[1]?[b]:[])]];}
 if(sql.startsWith('INSERT INTO bikes')){const id=nextId++;bikes.push({id,registration_number:p[4],profile:JSON.parse(p[9])});return [{insertId:id}];}
 if(sql.startsWith('INSERT INTO bike_images')){if(failImages)throw Error('photo write failed');images.push(p);return [{}];}
 if(sql.startsWith('UPDATE bike_import_batches')){batches.get(p[1]).result=p[0];return [{}];}
 throw Error('Unexpected SQL: '+sql);
},async getConnection(){return{query:pool.query,async beginTransaction(){snapshot={bikes:bikes.slice(),images:images.slice(),batches:new Map([...batches].map(([k,v])=>[k,{...v}]))};},async commit(){snapshot=null;if(loseCommit){loseCommit=false;throw Error('response lost');}},async rollback(){if(snapshot){bikes=snapshot.bikes;images=snapshot.images;batches.clear();for(const [k,v] of snapshot.batches)batches.set(k,v);snapshot=null;}},release(){}};}};
const dbPath=require.resolve('../src/config/db');require.cache[dbPath]={id:dbPath,filename:dbPath,loaded:true,exports:pool};
const users=require('../src/models/userModel');users.findById=async id=>({id,role:id===9?'dealer':'admin',is_active:1,is_verified:1});const tokens=require('../src/utils/tokens');const auth=id=>({Authorization:'Bearer '+tokens.signAccessToken({id,role:id===9?'dealer':'admin',email:'test@example.com'})});
before(async()=>{root=await fs.mkdtemp(path.join(os.tmpdir(),'bk-bulk-'));const uploadPath=require.resolve('../src/middleware/upload');require.cache[uploadPath]={id:uploadPath,filename:uploadPath,loaded:true,exports:{uploadRoot:root}};const app=require('express')();app.use('/bulk',require('../src/routes/bulkBikeRoutes'));app.use((e,req,res,next)=>res.status(e.status||500).json({error:e.message}));server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));base='http://127.0.0.1:'+server.address().port;});
after(async()=>{await new Promise(r=>server.close(r));await fs.rm(root,{recursive:true,force:true});});
async function preview(reg,photos,owner=1){const f=new FormData();f.set('sheet',new Blob([`brand,model,year,registrationNumber,keysCount,vehicleRating\nHonda,Activa,2024,${reg},0,4`]),'bikes.csv');if(photos)f.set('photos',new Blob([photos]),'photos.zip');const r=await fetch(base+'/bulk/preview',{method:'POST',headers:auth(owner),body:f});return {r,data:await r.json()};}
async function zipPhoto(reg){const archiver=require('archiver');return new Promise((resolve,reject)=>{const z=archiver('zip'),chunks=[];z.on('data',c=>chunks.push(c));z.on('end',()=>resolve(Buffer.concat(chunks)));z.on('error',reject);z.append(Buffer.from([255,216,255,217]),{name:reg+'/front.jpg'});z.finalize();});}
test('bulk routes require a current admin account and template downloads',async()=>{assert.equal((await fetch(base+'/bulk/template')).status,401);assert.equal((await fetch(base+'/bulk/template',{headers:auth(9)})).status,403);const r=await fetch(base+'/bulk/template',{headers:auth(1)});assert.equal(r.status,200);assert.match(r.headers.get('content-disposition'),/xlsx/);});
test('preview is owner-bound and confirm retries return the same generated IDs',async()=>{const {r,data}=await preview('KA01AB9001');assert.equal(r.status,200);assert.equal(data.canImport,true);assert.equal(bikes.length,0);assert.equal((await fetch(base+'/bulk/'+data.previewId+'/confirm',{method:'POST',headers:auth(2)})).status,404);const a=await (await fetch(base+'/bulk/'+data.previewId+'/confirm',{method:'POST',headers:auth(1)})).json();const b=await (await fetch(base+'/bulk/'+data.previewId+'/confirm',{method:'POST',headers:auth(1)})).json();assert.deepEqual(a,b);assert.equal(bikes.length,1);assert.equal(bikes[0].profile.keysCount,0);assert.equal((await preview('KA01AB9001')).data.canImport,false);});
test('photo/database failure rolls back bikes and removes only copied photos',async()=>{const {data}=await preview('KA01AB9002',await zipPhoto('KA01AB9002'));failImages=true;const r=await fetch(base+'/bulk/'+data.previewId+'/confirm',{method:'POST',headers:auth(1)});assert.equal(r.status,500);assert.equal(bikes.length,1);assert.deepEqual(await fs.readdir(path.join(root,'bikes')),[]);failImages=false;const retry=await fetch(base+'/bulk/'+data.previewId+'/confirm',{method:'POST',headers:auth(1)});assert.equal(retry.status,200);assert.equal(bikes.length,2);assert.equal(images.length,1);});
test('lost commit response retains committed photos and a retry returns stored result',async()=>{const {data}=await preview('KA01AB9003',await zipPhoto('KA01AB9003'));loseCommit=true;const r=await fetch(base+'/bulk/'+data.previewId+'/confirm',{method:'POST',headers:auth(1)});assert.equal(r.status,500);const files=await fs.readdir(path.join(root,'bikes'));assert.equal(files.length,2);const retry=await fetch(base+'/bulk/'+data.previewId+'/confirm',{method:'POST',headers:auth(1)});assert.equal(retry.status,200);assert.equal(bikes.length,3);assert.equal((await retry.json()).imported,1);});
test('expired previews and registrations added after preview cannot import',async()=>{let {data}=await preview('KA01AB9004',null,2);batches.get(data.previewId).expired=1;assert.equal((await fetch(base+'/bulk/'+data.previewId+'/confirm',{method:'POST',headers:auth(2)})).status,410);({data}=await preview('KA01AB9005',null,2));bikes.push({id:100,registration_number:'KA01AB9005'});assert.equal((await fetch(base+'/bulk/'+data.previewId+'/confirm',{method:'POST',headers:auth(2)})).status,409);});
