const test=require('node:test'),assert=require('node:assert/strict');const p=require('../src/utils/purchases');
test('purchase amounts and inspection fields validate before storing',()=>{assert.equal(p.finances({purchasePrice:'50000.50',paymentPaid:'20000'}).purchasePrice,'50000.50');for(const b of [{purchasePrice:'-1'},{paymentPaid:'1e8'}])assert.throws(()=>p.finances(b));assert.throws(()=>p.customer({phone:'bad'}));assert.throws(()=>p.vehicle({year:1800}));assert.throws(()=>p.vehicle({latitude:100,longitude:1}));assert.throws(()=>p.date('2026-02-30','date'));assert.equal(p.vehicle({detailProfile:{engineNoise:'No',vehicleRating:5}}).detailProfile.vehicleRating,5);});
test('executive record omits purchase finance and only contains inspection/customer work',()=>{const r={id:'task',customer:'{"name":"Customer","phone":"9900000000"}',vehicle:'{"brand":"Honda"}',finances:'{"purchasePrice":"100","paymentPaid":"30"}',purchase_date:'2026-10-07',bike_id:5};const staff=p.publicRecord(r,false);assert.equal(staff.finances,undefined);assert.equal(staff.payment,undefined);assert.equal(staff.purchase_date,undefined);assert.equal(staff.customer.phone,'9900000000');assert.equal(p.publicRecord(r,true).payment.balance,7000);});
test('submission requires inspection timestamp, camera photos and auction vehicle fields',()=>{const r={vehicle:JSON.stringify({brand:'Honda',model:'Activa',year:2024,registrationNumber:'KA01AA1234',inspectionCharges:{fineCost:0,paintingCost:0,damageCost:0,oilChangeCost:300,seatChangeCost:400,brakePadCost:200}}),customer:JSON.stringify({name:'Seller',phone:'9900000000'}),inspection_at:'2026-10-07 04:00:00'};assert.doesNotThrow(()=>p.validateSubmit(r,1));assert.throws(()=>p.validateSubmit(r,0));assert.throws(()=>p.validateSubmit({...r,inspection_at:null},1));assert.throws(()=>p.validateSubmit({...r,vehicle:'{}'},1));});
test('inventory inspection profile retains engine, chassis and registration details',()=>{const p=require('../src/utils/bikeProfile');const profile=p.parseProfile({engineNumber:'ENG123',chassisNumber:'FRAME123',registrationDate:'2024-04-05',inspectionNotes:'Checked engine'});assert.equal(p.readProfile(JSON.stringify(profile)).engineNumber,'ENG123');assert.throws(()=>p.parseProfile({registrationDate:'2026-02-30'}));});

test('Bengaluru zones accept only the five dispatch areas and survive executive edits',()=>{for(const z of ['North','East','West','South','Central'])assert.equal(p.zone(z),z);for(const z of ['',null,'Other'])assert.throws(()=>p.zone(z));assert.equal(p.vehicle({model:'Activa',inspectionZone:'West'},{inspectionZone:'North'}).inspectionZone,'North');});

test('inspection costs use exact totals, fixed transport and reject incomplete mandatory charges',()=>{const c=p.inspectionCharges({fineCost:'500.50',fineDetails:'Notice 123',paintingCost:'1200',paintingDetails:'Tank',damageCost:0,oilChangeCost:300,seatChangeCost:400,brakePadCost:200,transportCost:1,parts:[{name:'Mirror',cost:'150.25'}],totalPaise:1});assert.equal(c.transportCost,'1000');assert.equal(c.totalPaise,375075);assert.doesNotThrow(()=>p.requireCharges(c));assert.throws(()=>p.requireCharges({...c,oilChangeCost:null}));assert.throws(()=>p.requireCharges({...c,fineDetails:''}));assert.throws(()=>p.inspectionCharges({parts:[{name:'',cost:10}]}));assert.throws(()=>p.inspectionCharges({seatChangeCost:-1}));});

test('inspection references retain full UUID uniqueness and remain stable for every role',()=>{const ids=['1ce13c05-26fd-491d-b2e6-7ac0f3990a1f','1ce13c05-26fd-491d-b2e6-7ac0f3990a20','00000000-0000-4000-8000-000000000001'];const refs=ids.map(id=>p.publicRecord({id},true).reference);assert.equal(new Set(refs).size,ids.length);ids.forEach((id,i)=>{assert.equal(refs[i],p.publicRecord({id},false).reference);assert.equal(refs[i],'BK-INS-'+BigInt('0x'+id.replace(/-/g,'')).toString(36).toUpperCase());});assert.equal(p.publicRecord({id:'------------------------------------'},true).reference,'------------------------------------');});
