const {test,before,after}=require('node:test'),assert=require('node:assert/strict');Object.assign(process.env,{DB_HOST:'unused',DB_USER:'unused',DB_PASSWORD:'unused',DB_NAME:'unused',JWT_SECRET:'specialist-test',NODE_ENV:'test'});
const id='11111111-1111-4111-8111-111111111111',users=new Map([[1,{id:1,role:'admin',is_active:1,is_verified:1,admin_scopes:null}],[2,{id:2,role:'admin',is_active:1,is_verified:1,admin_scopes:'["purchase"]'}],[3,{id:3,role:'admin',is_active:1,is_verified:1,admin_scopes:'["mechanic"]'}],[4,{id:4,role:'admin',is_active:1,is_verified:1,admin_scopes:'["documents"]'}]]);let record={id,version:1,customer:'{"name":"Customer","phone":"9999999999"}',vehicle:'{"registrationNumber":"KA01AA1234"}',finances:'{"paymentPaid":50000}'},server,base;
const pool={query:async(sql,p=[])=>{if(sql.startsWith('SHOW COLUMNS'))return [[{Field:'admin_scopes'}]];if(sql.startsWith('CREATE TABLE')||sql.startsWith('INSERT INTO admin_settings')||sql.startsWith('INSERT INTO admin_activity'))return [[]];if(sql.startsWith('SELECT CAST(id AS CHAR)'))return [[{setting_value:'1'}]];if(sql.startsWith('SELECT id,role,'))return [[users.get(Number(p[0]))].filter(Boolean)];if(sql.startsWith('SELECT id,bike_id,')||sql.startsWith('SELECT * FROM bike_purchases'))return [[record]];if(sql.startsWith('UPDATE bike_purchases SET vehicle')){record.vehicle=p[0];record.version++;return [{}];}throw Error(sql);},getConnection:async()=>({query:(...a)=>pool.query(...a),beginTransaction:async()=>{},commit:async()=>{},rollback:async()=>{},release(){}})};
const db=require.resolve('../src/config/db');require.cache[db]={id:db,filename:db,loaded:true,exports:pool};const tokens=require('../src/utils/tokens'),headers=n=>({Authorization:'Bearer '+tokens.signAccessToken({id:n,role:'admin'}),'Content-Type':'application/json'});
before(async()=>{const app=require('express')();app.use(require('express').json());app.use('/s',require('../src/routes/specialistRoutes'));app.use((e,req,res,next)=>res.status(e.status||500).json({error:e.message}));server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));base='http://127.0.0.1:'+server.address().port;});after(async()=>new Promise(r=>server.close(r)));
const get=(u,role)=>fetch(base+'/s/'+role,{headers:headers(u)}),patch=(u,role,body)=>fetch(base+'/s/'+role+'/'+id,{method:'PATCH',headers:headers(u),body:JSON.stringify({version:record.version,...body})});
test('server denies direct access across specialist workspaces and strips actual payments',async()=>{assert.equal((await get(2,'mechanic')).status,403);assert.equal((await get(3,'documents')).status,403);assert.equal((await get(4,'purchase')).status,403);const d=await(await get(2,'purchase')).json();assert.equal(d.rows[0].finances,undefined);assert.equal((await get(1,'documents')).status,200);});
test('purchase proposal saves separately and payment mutations are forbidden',async()=>{assert.equal((await patch(2,'purchase',{proposedPrice:'60000',notes:'Customer quotation'})).status,200);assert.equal(JSON.parse(record.vehicle).purchaseProposal.amount,'60000.00');assert.equal(record.finances,'{"paymentPaid":50000}');assert.equal((await patch(2,'purchase',{proposedPrice:'1',finances:{paymentPaid:1}})).status,403);assert.equal((await patch(4,'documents',{proposedPrice:'1'})).status,403);});
test('mechanic estimates require mandatory charges and enforce fixed transport',async()=>{assert.equal((await patch(3,'mechanic',{inspectionCharges:{oilChangeCost:100}})).status,400);const c={fineCost:0,paintingCost:0,damageCost:0,oilChangeCost:300,seatChangeCost:400,brakePadCost:200,transportCost:0,parts:[{name:'Mirror',cost:100}]};assert.equal((await patch(3,'mechanic',{inspectionCharges:c,notes:'Reviewed'})).status,200);const v=JSON.parse(record.vehicle);assert.equal(v.inspectionCharges.totalPaise,200000);assert.equal(v.inspectionCharges.transportCost,'1000');assert.equal(record.finances,'{"paymentPaid":50000}');assert.equal((await patch(3,'mechanic',{inspectionCharges:c,paymentPaid:100})).status,403);});
