const {test,before,after}=require('node:test'),assert=require('node:assert/strict');Object.assign(process.env,{DB_HOST:'unused',DB_USER:'unused',DB_PASSWORD:'unused',DB_NAME:'unused',JWT_SECRET:'winner-test-secret',NODE_ENV:'test'});
const winner={id:1,bike_id:2,winner_id:3,highest_bid:55000,brand:'Honda',model:'Activa',registration_number:'KA01AB1234',full_name:'Dealer',email:'dealer@example.com',phone:'9876543210',closed_at:new Date(),business_name:'Dealer Bikes'},contacts=new Map();const pool={query:async(sql,p=[])=>{
 if(sql.startsWith('SHOW COLUMNS'))return [[{Field:'phone'},{Field:'business_name'},{Field:'gst_number'}]];
 if(sql.startsWith('CREATE TABLE'))return [{}];
 if(sql.startsWith('SELECT a.id')){assert.ok(sql.includes("a.status='closed' AND a.result='sold'"));return [[...(sql.includes('AND a.id=?')&&p[0]!==1?[]:[winner])]];}
 if(sql.startsWith('SELECT COUNT'))return [[{total:1}]];
 if(sql.startsWith('SELECT id,auction_id'))return [[...contacts.values()]];
 if(sql.startsWith('INSERT INTO auction_winner_contacts')){contacts.set(p[0],{id:p[0],auction_id:p[1],admin_id:p[2],channel:p[3],recipient:p[4],message:p[5],created_at:new Date(),marked_sent_at:null});return [{}];}
 if(sql.startsWith('UPDATE auction_winner_contacts')){const c=contacts.get(p[1]);if(c&&!c.marked_sent_at)c.marked_sent_at=new Date();return [{affectedRows:c?1:0}];}
 if(sql.startsWith('SELECT id FROM auction_winner_contacts'))return [[...(contacts.has(p[0])?[{id:p[0]}]:[])]];throw Error(sql);
}};
const dbPath=require.resolve('../src/config/db');require.cache[dbPath]={id:dbPath,filename:dbPath,loaded:true,exports:pool};const users=require('../src/models/userModel');users.findById=async id=>({id,role:Number(id)===9?'dealer':'admin',is_active:1,is_verified:1});const tokens=require('../src/utils/tokens');const headers=id=>({Authorization:'Bearer '+tokens.signAccessToken({id,role:'admin',email:'admin@example.com'}),'Content-Type':'application/json'});let server,base;
before(async()=>{const app=require('express')();app.use(require('express').json());app.use('/winners',require('../src/routes/winnerRoutes'));app.use((e,req,res,next)=>res.status(e.status||500).json({error:e.message}));server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));base='http://127.0.0.1:'+server.address().port;});after(async()=>new Promise(r=>server.close(r)));
test('winner data is admin-only using the current account role',async()=>{assert.equal((await fetch(base+'/winners')).status,401);assert.equal((await fetch(base+'/winners',{headers:headers(9)})).status,403);const data=await (await fetch(base+'/winners',{headers:headers(1)})).json();assert.equal(data.rows[0].phone,'9876543210');assert.equal(data.rows[0].whatsappAvailable,true);assert.equal(contacts.size,0);});
test('only explicit admin draft requests prepare contact records and never mark delivery automatically',async()=>{const res=await fetch(base+'/winners/1/draft',{method:'POST',headers:headers(1),body:JSON.stringify({channel:'whatsapp',instructions:'Please call us to arrange payment.'})});assert.equal(res.status,200);const data=await res.json();assert.equal(data.status,'draft_prepared');assert.match(data.url,/https:\/\/wa.me\/919876543210/);assert.equal(contacts.get(data.contactId).marked_sent_at,null);assert.equal(contacts.get(data.contactId).admin_id,'1');});
test('admins can record a sent message explicitly and invalid winner/channel requests fail',async()=>{const id=[...contacts.keys()][0];let r=await fetch(base+'/winners/contacts/'+id+'/mark-sent',{method:'POST',headers:headers(1)});assert.equal(r.status,200);const date=contacts.get(id).marked_sent_at;r=await fetch(base+'/winners/contacts/'+id+'/mark-sent',{method:'POST',headers:headers(1)});assert.equal(r.status,200);assert.equal(contacts.get(id).marked_sent_at,date);for(const [winnerId,channel,status] of [[99,'email',404],[1,'sms',400]]){r=await fetch(base+'/winners/'+winnerId+'/draft',{method:'POST',headers:headers(1),body:JSON.stringify({channel,instructions:'Pay after calling.'})});assert.equal(r.status,status);}});
