const crypto=require('node:crypto');
const scopes=['inventory','auctions','notifications','purchase','documents','mechanic'];
const textFields={pickupLocation:500,pickupMapUrl:500,pickupContact:190,pickupInstructions:1000,collectedBy:190,collectorPhone:20,deliveryNotes:1000,documentNotes:1000};
const enumFields={rcProgress:['Pending','Received','Handed over'],nocProgress:['Not required','Pending','Received','Handed over'],hpProgress:['Not required','Pending','Cleared'],transferProgress:['Pending','Submitted','Completed']};
const moneyFields=['purchasePrice','transportCost','repairCost','documentCost','otherCost'];
function error(message,status=400){const e=new Error(message);e.status=status;e.expose=true;throw e;}
function cents(value){if(value==null||value==='')return null;const v=String(value);if(!/^\d{1,10}(\.\d{1,2})?$/.test(v))error('Use a non-negative amount with up to two decimals');const [a,b='']=v.split('.');return Number(a)*100+Number(b.padEnd(2,'0'));}
function financial(sale,winningPrice){const price=cents(sale.salePrice??winningPrice),received=cents(sale.paymentReceived),costs=moneyFields.map(k=>cents(sale[k]));const total=costs.some(x=>x!==null)?costs.reduce((a,b)=>a+(b??0),0):null;return {price,received,balance:price===null?null:price-(received??0),paymentStatus:price===null?'Not recorded':received===null||received===0?'Pending':received<price?'Part-paid':'Paid',totalCost:total,profit:price===null||costs[0]===null?null:price-(total??0)};}
function parseOperations(body,sale){const result={...sale};for(const key of [...Object.keys(textFields),...Object.keys(enumFields),...moneyFields,'paymentDeadline','documentDeadline','paymentConfirmed','deliveryReleased','receiptSigned','pickupReady']){if(!Object.hasOwn(body,key))continue;let v=body[key];if(v===null&&!['paymentConfirmed','deliveryReleased','receiptSigned','pickupReady'].includes(key)){result[key]=null;continue;}if(['paymentConfirmed','deliveryReleased','receiptSigned','pickupReady'].includes(key)){if(typeof v!=='boolean')error('Invalid '+key);result[key]=v;continue;}if(typeof v!=='string'&&typeof v!=='number')error('Invalid '+key);v=String(v).trim();if(!v){result[key]=null;continue;}if(key==='pickupMapUrl'){let url;try{url=new URL(v);}catch{error('Use an HTTPS pickup map link');}if(url.protocol!=='https:'||url.username||url.password)error('Use an HTTPS pickup map link');}
if(textFields[key]&&v.length>textFields[key])error(key+' is too long');if(enumFields[key]&&!enumFields[key].includes(v))error('Invalid '+key);if(moneyFields.includes(key))cents(v);if(key.endsWith('Deadline')&&(!/^\d{4}-\d{2}-\d{2}$/.test(v)||!Number.isFinite(Date.parse(v))||new Date(v).toISOString().slice(0,10)!==v))error('Invalid '+key);result[key]=v;}return result;}
function validateRelease(sale,winningPrice){if(!sale.deliveryReleased)return;const f=financial(sale,winningPrice);if(!sale.paymentConfirmed||f.price===null||f.price<=0||f.balance>0)error('Confirm full payment before releasing the bike',409);if(!sale.receiptSigned)error('Confirm the sale receipt is signed before release',409);if(!sale.collectedBy||!sale.deliveryDate)error('Collector name and delivery date are required',409);const docs=sale.documents||[];if(!docs.some(d=>d.kind==='deliveryPhoto')||!docs.some(d=>d.kind==='saleReceipt'))error('Upload a delivery photo and signed sale receipt before release',409);}
function permissions(raw){if(raw===null||raw===undefined)return [];try{const a=typeof raw==='string'?JSON.parse(raw):raw;return Array.isArray(a)?a.filter(s=>scopes.includes(s)):[];}catch{return [];}}
const pending=new WeakMap();async function ensureOperations(pool){if(pending.has(pool))return pending.get(pool);const p=(async()=>{const [cols]=await pool.query('SHOW COLUMNS FROM users');if(!cols.some(c=>c.Field==='admin_scopes'))try{await pool.query('ALTER TABLE users ADD COLUMN admin_scopes TEXT NULL');}catch(e){if(e.code!=='ER_DUP_FIELDNAME')throw e;}await pool.query("CREATE TABLE IF NOT EXISTS admin_settings (setting_key VARCHAR(64) PRIMARY KEY, setting_value VARCHAR(64) NOT NULL) ENGINE=InnoDB");await pool.query("INSERT INTO admin_settings (setting_key,setting_value) SELECT 'primary_admin_id',CAST(id AS CHAR) FROM users WHERE role='admin' AND LOWER(email)='admin@bikeskart.com' LIMIT 1 ON DUPLICATE KEY UPDATE setting_value=VALUES(setting_value)");await pool.query(`CREATE TABLE IF NOT EXISTS admin_activity (id CHAR(36) PRIMARY KEY, actor_id VARCHAR(32) NOT NULL, action VARCHAR(100) NOT NULL, entity_id VARCHAR(64) NULL, changes LONGTEXT NULL, created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), KEY activity_time(created_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`);await pool.query(`CREATE TABLE IF NOT EXISTS auction_confirmations (auction_id BIGINT UNSIGNED PRIMARY KEY, confirmed_by VARCHAR(32) NOT NULL, confirmed_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`);})();pending.set(pool,p);try{await p;}catch(e){pending.delete(pool);throw e;}}
async function primaryAdminId(pool){await ensureOperations(pool);const [[row]]=await pool.query("SELECT CAST(id AS CHAR) AS setting_value FROM users WHERE role='admin' AND LOWER(email)='admin@bikeskart.com' LIMIT 1");return row?.setting_value;}
function effectivePermissions(user,ownerId){return String(user.id)===String(ownerId)?['owner','accounts',...scopes]:permissions(user.admin_scopes);}
function privateBike(bike,isOwner){if(isOwner||!bike)return bike;const result={...bike};for(const key of ['sale_profile','financial','buyer_name','buyer_phone','buyer_email','buyer_business','rc_document_url'])delete result[key];return result;}
async function audit(pool,actor,action,id,changes){await pool.query('INSERT INTO admin_activity (id,actor_id,action,entity_id,changes) VALUES (?,?,?,?,?)',[crypto.randomUUID(),String(actor),action,String(id??''),JSON.stringify(changes??{})]);}
module.exports={scopes,primaryAdminId,effectivePermissions,privateBike,moneyFields,textFields,enumFields,cents,financial,parseOperations,validateRelease,permissions,ensureOperations,audit,error};
