const fs=require('node:fs/promises'),path=require('node:path'),crypto=require('node:crypto');const {spawn}=require('node:child_process');
const root=process.env.BACKUP_ROOT?path.resolve(process.env.BACKUP_ROOT):path.join(path.dirname(require('../middleware/upload').uploadRoot),'private-backups');
const uploadRoot=require('../middleware/upload').uploadRoot;
if(root===uploadRoot||root.startsWith(uploadRoot+path.sep))throw Error('BACKUP_ROOT must be outside uploaded/public files');
let running=null,lastError=null,lastSuccess=null;
function run(command,args){return new Promise((resolve,reject)=>{const p=spawn(command,args,{stdio:['ignore','ignore','pipe']});let stderr='';p.stderr.on('data',b=>{stderr+=b.toString().slice(0,1000);});p.on('error',reject);p.on('close',code=>code===0?resolve():reject(new Error(command+' failed: '+stderr)));});}
async function list(){await fs.mkdir(root,{recursive:true,mode:0o700});const names=(await fs.readdir(root)).filter(n=>/^bk-backup-\d{13}-[a-f0-9]{8}\.tar\.gz$/.test(n));return Promise.all(names.sort().reverse().map(async name=>({name,size:(await fs.stat(path.join(root,name))).size})));}
async function backup(pool){if(running)return running;running=(async()=>{await fs.mkdir(root,{recursive:true,mode:0o700});const name='bk-backup-'+Date.now()+'-'+crypto.randomBytes(4).toString('hex'),stage=path.join(root,'.'+name),archive=path.join(root,name+'.tar.gz'),c=await pool.getConnection();let committed=false;try{await fs.mkdir(stage,{mode:0o700});await c.query('SET TRANSACTION ISOLATION LEVEL REPEATABLE READ');await c.query('START TRANSACTION WITH CONSISTENT SNAPSHOT');const [tables]=await c.query("SHOW FULL TABLES WHERE Table_type='BASE TABLE'");const manifest={version:1,createdAt:new Date().toISOString(),tables:[],uploads:'uploads',format:'JSON data plus SHOW CREATE TABLE, tar.gz'};for(const entry of tables){const table=Object.values(entry)[0];if(!/^[A-Za-z0-9_]+$/.test(table))throw Error('Unsupported database table name');const [rows]=await c.query('SELECT * FROM `'+table+'`');const [[ddl]]=await c.query('SHOW CREATE TABLE `'+table+'`');await fs.writeFile(path.join(stage,table+'.json'),JSON.stringify({table,create:Object.values(ddl)[1],rows}),{mode:0o600});manifest.tables.push({name:table,rows:rows.length});}await c.commit();committed=true;await fs.cp(require('../middleware/upload').uploadRoot,path.join(stage,'uploads'),{recursive:true});await fs.writeFile(path.join(stage,'manifest.json'),JSON.stringify(manifest,null,2),{mode:0o600});await run('tar',['-czf',archive,'-C',stage,'.']);await fs.chmod(archive,0o600);lastSuccess=manifest.createdAt;lastError=null;await fs.rm(stage,{recursive:true,force:true});const files=await list();for(const file of files.slice(14))await fs.unlink(path.join(root,file.name));return {name:name+'.tar.gz',createdAt:lastSuccess};}catch(e){if(!committed)await c.rollback();await fs.rm(stage,{recursive:true,force:true});await fs.rm(archive,{force:true});lastError=e.message;throw e;}finally{c.release();}})().finally(()=>{running=null;});return running;}
function startScheduler(pool){const check=async()=>{try{const files=await list();const newest=files[0]?.name.match(/bk-backup-(\d{13})/);if(!newest||Date.now()-Number(newest[1])>=24*60*60*1000)await backup(pool);}catch(e){lastError=e.message;console.error('Scheduled backup failed:',e.message);}};check();setInterval(check,60*60*1000).unref();}
module.exports={root,list,backup,startScheduler,status:()=>({running:!!running,lastSuccess,lastError,intervalHours:24,retention:14,storage:'Private server storage; download a copy for off-server protection'})};
