const {error,cents}=require('./adminOperations');const {parseProfile}=require('./bikeProfile');
const pending=new WeakMap();
async function ensurePurchases(pool){if(pending.has(pool))return pending.get(pool);const p=(async()=>{const [columns]=await pool.query('SHOW COLUMNS FROM users');const role=columns.find(c=>c.Field==='role');if(role?.Type?.startsWith('enum(')&&!role.Type.includes("'executive'")){if(!/^enum\('[a-z_]+'(?:,'[a-z_]+')*\)$/.test(role.Type))throw Error('Unexpected user role enum');await pool.query('ALTER TABLE users MODIFY COLUMN role '+role.Type.slice(0,-1)+",'executive') NOT NULL");}await pool.query(`CREATE TABLE IF NOT EXISTS bike_purchases (id CHAR(36) PRIMARY KEY, customer LONGTEXT NOT NULL, vehicle LONGTEXT NOT NULL, finances LONGTEXT NOT NULL, purchase_date DATE NULL, location VARCHAR(500) NULL, inspection_at DATETIME NULL, assigned_to BIGINT UNSIGNED NULL, status VARCHAR(20) NOT NULL DEFAULT 'draft', bike_id BIGINT UNSIGNED NULL, created_by VARCHAR(32) NOT NULL, submitted_at DATETIME NULL, approved_by VARCHAR(32) NULL, approved_at DATETIME NULL, version INT NOT NULL DEFAULT 1, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, UNIQUE KEY purchase_bike(bike_id), KEY inspection_assignee(assigned_to,status)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`);await pool.query(`CREATE TABLE IF NOT EXISTS purchase_documents (id CHAR(36) PRIMARY KEY,purchase_id CHAR(36) NOT NULL,kind VARCHAR(30) NOT NULL,filename VARCHAR(100) NOT NULL,uploaded_by VARCHAR(32) NOT NULL,captured_at VARCHAR(40) NULL,capture_source VARCHAR(30) NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,KEY purchase_files(purchase_id,kind)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4`);})();pending.set(pool,p);try{await p;}catch(e){pending.delete(pool);throw e;}}
function text(v,max,label){if(v==null||v==='')return null;if(typeof v!=='string'||v.trim().length>max)error('Invalid '+label);return v.trim()||null;}
function date(v,label){if(!v)return null;if(typeof v!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(v)||!Number.isFinite(Date.parse(v))||new Date(v).toISOString().slice(0,10)!==v)error('Invalid '+label);return v;}
function customer(body,old={}){const result={...old};for(const [k,max] of Object.entries({name:150,phone:20,email:190,address:1000,kycType:50}))if(Object.hasOwn(body,k))result[k]=text(body[k],max,k);if(result.phone&&!/^\+?[\d ()-]{7,20}$/.test(result.phone))error('Invalid mobile');if(result.email&&!/^\S+@\S+\.\S+$/.test(result.email))error('Invalid email');return result;}
const zones=['North','East','West','South','Central'];
function zone(value){if(!zones.includes(value))error('Choose Bengaluru North, East, West, South or Central');return value;}
function inspectionCharges(body){if(!body||typeof body!=='object'||Array.isArray(body))error('Invalid inspection charges');const result={transportCost:'1000',fineDetails:text(body.fineDetails,3000,'fine details'),paintingDetails:text(body.paintingDetails,3000,'painting details'),damageDetails:text(body.damageDetails,3000,'damage details')};for(const key of ['fineCost','paintingCost','damageCost','oilChangeCost','seatChangeCost','brakePadCost']){const value=body[key],amount=cents(value);result[key]=amount===null?null:(amount/100).toFixed(2);}if(body.parts!=null&&!Array.isArray(body.parts))error('Invalid replacement parts');if((body.parts||[]).length>30)error('Maximum 30 replacement parts');result.parts=(body.parts||[]).map(part=>{const name=text(part.name,150,'part name'),amount=cents(part.cost);if(!name||amount===null)error('Each replacement part needs a name and cost');return {name,cost:(amount/100).toFixed(2)};});result.totalPaise=100000+['fineCost','paintingCost','damageCost','oilChangeCost','seatChangeCost','brakePadCost'].reduce((sum,key)=>sum+(cents(result[key])||0),0)+result.parts.reduce((sum,part)=>sum+cents(part.cost),0);return result;}
function requireCharges(charges){if(!charges)error('Complete inspection charges before submission');const c=inspectionCharges(charges);for(const key of ['fineCost','paintingCost','damageCost','oilChangeCost','seatChangeCost','brakePadCost'])if(c[key]===null)error('Enter '+key+' (use 0 where there is no charge)');if(cents(c.fineCost)>0&&!c.fineDetails)error('Enter notice / fine details');if(cents(c.paintingCost)>0&&!c.paintingDetails)error('Describe painting required');if(cents(c.damageCost)>0&&!c.damageDetails)error('Describe other damage repairs');return c;}
function vehicle(body,old={}){const result={...old};for(const [k,max] of Object.entries({brand:150,model:150,registrationNumber:30,fuelType:30,conditionNotes:10000,engineNumber:80,chassisNumber:80,inspectionNotes:5000}))if(Object.hasOwn(body,k))result[k]=text(body[k],max,k);for(const [k,min,max] of [['year',1950,new Date().getFullYear()+1],['kilometersDriven',0,2147483647],['ownershipCount',1,255]])if(Object.hasOwn(body,k)){if(body[k]===''||body[k]===null)result[k]=null;else{const n=Number(body[k]);if(!['string','number'].includes(typeof body[k])||!Number.isInteger(n)||n<min||n>max)error('Invalid '+k);result[k]=n;}}if(Object.hasOwn(body,'inspectionCharges'))result.inspectionCharges=inspectionCharges(body.inspectionCharges);result.detailProfile=parseProfile(body.detailProfile||{},old.detailProfile);if(Object.hasOwn(body,'registrationDate'))result.registrationDate=date(body.registrationDate,'registration date');if(Object.hasOwn(body,'latitude')||Object.hasOwn(body,'longitude')){const lat=Number(body.latitude),lng=Number(body.longitude);if(body.latitude==null&&body.longitude==null){result.latitude=null;result.longitude=null;}else{if(!Number.isFinite(lat)||!Number.isFinite(lng)||lat< -90||lat>90||lng< -180||lng>180)error('Invalid location coordinates');result.latitude=lat;result.longitude=lng;}}return result;}
function finances(body,old={}){const result={...old};for(const k of ['purchasePrice','paymentPaid','transportCost','documentCost','otherCost'])if(Object.hasOwn(body,k)){const c=cents(body[k]);result[k]=c===null?null:String(body[k]);}for(const [k,max] of Object.entries({paymentMethod:30,paymentReference:190,paymentNotes:1000}))if(Object.hasOwn(body,k))result[k]=text(body[k],max,k);if(Object.hasOwn(body,'paymentDate'))result.paymentDate=date(body.paymentDate,'payment date');return result;}
function json(raw){try{return typeof raw==='string'?JSON.parse(raw):raw||{};}catch{return {};}}
function publicRecord(row,owner){const result={...row,reference:(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(String(row.id))?'BK-INS-'+BigInt('0x'+String(row.id).replace(/-/g,'')).toString(36).toUpperCase():String(row.id||'')),customer:json(row.customer),vehicle:json(row.vehicle)};delete result.finances;if(result.vehicle.inspectionCharges)result.vehicle.inspectionCharges=inspectionCharges(result.vehicle.inspectionCharges);if(owner){result.finances=json(row.finances);const price=cents(result.finances.purchasePrice),paid=cents(result.finances.paymentPaid);result.payment={price,paid,balance:price===null?null:price-(paid??0)};}else{delete result.purchase_date;delete result.bike_id;delete result.created_by;delete result.approved_by;delete result.approved_at;}return result;}
function validateSubmit(record,photos){const v=json(record.vehicle),c=json(record.customer);if(!v.brand||!v.model||!v.year||!v.registrationNumber||!c.name||!c.phone)error('Complete customer name/mobile and bike brand, model, year and registration before submission');if(!record.inspection_at)error('Inspection date and time are required');if(!photos)error('Capture at least one bike photo inside this application');requireCharges(v.inspectionCharges);}
module.exports={ensurePurchases,inspectionCharges,requireCharges,zones,zone,customer,vehicle,finances,date,text,json,publicRecord,validateSubmit};
